### ISSUE TITLE
Test ESP-Hosted with ESP32-C3-DEVKITM-1U

### ISSUE THREAD

**Issue by jvasanthan** [espressif/esp-hosted#112]
Hi, 
Can we evaluate esp-hosted solution with ESP32-C3-DEVKITM-1U kit? are there any limitations?

**Comment by ajita02** [comment]
Hi @jvasanthan,

Yes, You can. Ideally there should not be any limitation.

Thanks,
Ajita

**Comment by jvasanthan** [comment]
Hi @ajita02 , 
Thank you for the clarification.

**Comment by ajita02** [comment]
Hi @jvasanthan  ,

Welcome. Can you please close this issue, if your doubt is solved.

Thanks,
Ajita
