### ISSUE TITLE
Help with porting to sunxi platform

### ISSUE THREAD

**Issue by gpanasco** [espressif/esp-hosted#117]
Hello. 

I am currently trying to port esp-hosted to a custom-made board (not rpi), based on Armbian (nanopi neo core, Allwinner H3 processor). Picture of setup: https://pasteboard.co/LjKnzNhbejkh.jpg. I made a pcb that breaks out the esp directly to the sd card connector on the nanopi (sdio mode). I am aware that rpi is the main target for this project, however upon inspection of the source code I thought it would be easy to port. However, while I believe I have made great progress, something still seems to not be working correctly. 

Kernel: custom-built based on Armbian Debian 10 - 5.10.75

I will try to briefly explain all the steps I took:

1. Flashed ESP32-WROOM-32U with prebuilt binaries using windows flasher as follows: https://pasteboard.co/e1FERLbtdKHh.png - erase - flash - ok.
2. clone esp-hosted repo and initialized submodules (protobuf) & installed dependencies (bluetooth, etc), except specific ones for raspberry.
3. compiled test software (c and python), no problems (compiled directly on nanopi - did not cross-compile)
4. compiled driver using: `make target=sdio CROSS_COMPILE=/usr/bin/arm-linux-gnueabihf- KERNEL="/lib/modules/$(uname -r)/build" ARCH=arm` - have linux kernel headers installed. Build log:

```
rm -rf *.o sdio/*.o spi/*.o *.ko
make ARCH=arm CROSS_COMPILE=/usr/bin/arm-linux-gnueabihf- -C /lib/modules/5.10.75-sunxi/build M=/home/auro/tmp/esp-hosted/host/linux/host_driver/esp32 clean
make[1]: Entering directory '/usr/src/linux-headers-5.10.75-sunxi'
make[1]: Leaving directory '/usr/src/linux-headers-5.10.75-sunxi'
make ARCH=arm CROSS_COMPILE=/usr/bin/arm-linux-gnueabihf- -C /lib/modules/5.10.75-sunxi/build M=/home/auro/tmp/esp-hosted/host/linux/host_driver/esp32 modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.75-sunxi'
  CC [M]  /home/auro/tmp/esp-hosted/host/linux/host_driver/esp32/esp_bt.o
  CC [M]  /home/auro/tmp/esp-hosted/host/linux/host_driver/esp32/main.o
  CC [M]  /home/auro/tmp/esp-hosted/host/linux/host_driver/esp32/sdio/esp_sdio.o
  CC [M]  /home/auro/tmp/esp-hosted/host/linux/host_driver/esp32/sdio/esp_sdio_api.o
  CC [M]  /home/auro/tmp/esp-hosted/host/linux/host_driver/esp32/esp_serial.o
  CC [M]  /home/auro/tmp/esp-hosted/host/linux/host_driver/esp32/esp_rb.o
  LD [M]  /home/auro/tmp/esp-hosted/host/linux/host_driver/esp32/esp32_sdio.o
  MODPOST /home/auro/tmp/esp-hosted/host/linux/host_driver/esp32/Module.symvers
  CC [M]  /home/auro/tmp/esp-hosted/host/linux/host_driver/esp32/esp32_sdio.mod.o
  LD [M]  /home/auro/tmp/esp-hosted/host/linux/host_driver/esp32/esp32_sdio.ko

```
5. After running depmod (without it I got symbol errors), installed kernel module: `insmod esp32_sdio.ko resetpin=17` - my reset pin is 17, however I also tried it without the resetpin parameter (looking at the driver code I understood it ignores reset if not provided), but same problems. My reset signal enters the esp breakout board from the bottom via a pin header (not seen on the picture at the beginning of the post). lsmod gives me:
```
Module                  Size  Used by
esp32_sdio             24576  0
tun                    40960  2
pps_ldisc              20480  0
bnep                   24576  2
sun4i_gpadc_iio        16384  0
industrialio           53248  1 sun4i_gpadc_iio
btsdio                 20480  0
sun8i_thermal          16384  0
bluetooth             417792  10 btsdio,esp32_sdio,bnep
ecdh_generic           16384  1 bluetooth
sunxi_cedrus           32768  0
rfkill                 20480  3 bluetooth
v4l2_mem2mem           20480  1 sunxi_cedrus
videobuf2_dma_contig    20480  1 sunxi_cedrus
ecc                    28672  1 ecdh_generic
videobuf2_memops       20480  1 videobuf2_dma_contig
videobuf2_v4l2         20480  2 sunxi_cedrus,v4l2_mem2mem
videobuf2_common       40960  3 sunxi_cedrus,v4l2_mem2mem,videobuf2_v4l2
evdev                  20480  1
pps_gpio               16384  0
uio_pdrv_genirq        20480  0
uio                    16384  1 uio_pdrv_genirq
cpufreq_dt             20480  0
zram                   24576  2
usb_f_acm              20480  1
u_serial               24576  3 usb_f_acm
g_serial               16384  0
libcomposite           45056  2 g_serial,usb_f_acm
sunrpc                339968  1
ip_tables              24576  0
x_tables               24576  1 ip_tables
autofs4                36864  2
spidev                 20480  2
sunxi                  16384  0
phy_generic            20480  2 sunxi
gpio_keys              20480  0
```
6. ran `sudo mknod /dev/esps0 c 221 0; sudo chmod 666 /dev/esps0` to create char devs.
7. running dmesg returns:
```
[  458.618066] esp32_sdio: loading out-of-tree module taints kernel.
[  458.618721] esp32_sdio: module verification failed: signature and/or required key missing - tainting kernel
[  458.620092] esp_reset, ESP32: Resetpin of Host is 17
[  458.620257] esp_reset, ESP32: Triggering ESP reset.
[  458.620967] esp_sdio: probe of mmc0:0001:1 failed with error -110
[  459.212932] mmc0: card 0001 removed
[  459.975389] sunxi-mmc 1c0f000.mmc: fatal err update clk timeout
[  460.739422] sunxi-mmc 1c0f000.mmc: fatal err update clk timeout
[  461.491455] sunxi-mmc 1c0f000.mmc: fatal err update clk timeout
[  462.243487] sunxi-mmc 1c0f000.mmc: fatal err update clk timeout
[  463.324805] mmc0: queuing unknown CIS tuple 0x01 (3 bytes)
[  463.332124] mmc0: queuing unknown CIS tuple 0x1a (5 bytes)
[  463.335763] mmc0: queuing unknown CIS tuple 0x1b (8 bytes)
[  463.337705] mmc0: queuing unknown CIS tuple 0x80 (1 bytes)
[  463.337778] mmc0: queuing unknown CIS tuple 0x81 (1 bytes)
[  463.337842] mmc0: queuing unknown CIS tuple 0x82 (1 bytes)
[  463.339125] mmc0: queuing unknown CIS tuple 0x80 (1 bytes)
[  463.339194] mmc0: queuing unknown CIS tuple 0x81 (1 bytes)
[  463.339258] mmc0: queuing unknown CIS tuple 0x82 (1 bytes)
[  463.339447] mmc0: new SDIO card at address 0001
[  463.340279] esp_probe: ESP network device detected
```
Comparing my output with the one documented on esp-hosted guide, I noticed that "Features supported are: * WLAN * BT/BLE" log does NOT appear on my system.
8. Running ip a gives me:
```
4: ethsta0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
5: ethap0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
```
9. Running hciconfig gives me:
```
hci0:   Type: Primary  Bus: SDIO
        BD Address: 00:00:00:00:00:00  ACL MTU: 0:0  SCO MTU: 0:0
        DOWN
        RX bytes:0 acl:0 sco:0 events:0 errors:0
        TX bytes:0 acl:0 sco:0 commands:0 errors:0
```
10. Trying to run test.py or test.out (c test helper sw) hangs both python and c test programs.

I am really at a loss of where the problem may be. It may be possible that it is a hardware issue, however the breakout board is really simple (only breaks out sdio to ESP32) and the nanopi boots from a normal sd card on the SDIO interface, which means its hardware is totally functional. Voltages seem ok, reset pin is high (and toggles when loading kernel module). 

It may also be that I am totally stupid and some additional configuration step is necessary or I did not get how to use the test.py software.

I would really appreciate any tips on how to further address the issue.

Thanks!

**Comment by mantriyogesh** [comment]
Thank you, @gpanasco, for your kind words.
