### ISSUE TITLE
New ESP32-C3-Mini-1 INIT Event not received

### ISSUE THREAD

**Issue by anoop18pant** [espressif/esp-hosted#119]
We are using `ESP32-C3-DevKitM-1 v1.0 with ESP32-C3-Mini-1 v1.1 module` with our iMX7 based custom SBC to implement SPI based ESP-hosted solution. We had purchased 1 kit in Jan 2022, and we tested our solution and got everything working.
We ordered recently 3 more kits, and none of them are working (We don't receive INIT event on Host). We are using Release v0.4 of ESP hosted project. We have one SBC board, with ESP hosted driver and device tree and old ESP32 devkit working. But if we just replace the old ESP32 devkit with new ESP32 devkit, we don't receive the INIT event. By visual inspection, there is no difference in both old and new kits.
To further diagnose the issue, we followed the detailed advice given in https://github.com/espressif/esp-hosted/issues/101#issuecomment-1043053188. We tested and find that everything is correct upto these steps `Device Tree, Verify SPI is working, Disable spidev`. But when we go to the step `Load hosted project`, the driver esp32_spi is loaded successfully and we are also able to verify that ESP32 kit is getting reset. But at the Host side, INIT event is not received.
We also compared all 7 signals (MOSI, MISO, SCLK, CS, HANDSHAKE, READY, RESET) in CRO for new kit and we are able to see activity on each signal. So we assume that it's not a case of just some missing pin or track.
This sounds very strange that there is difference between the same product purchased at different time. Could you please help us in solving this issue.

++++++++++++++++
hi Yogesh,

We have set SPI mode on ESP32(Slave in our case) to MODE 3 and Our host deriver(Master in our case) was also set to SPI mode 3. This setting was not working.
After that we have changed it to following:
We have set SPI mode on ESP32(Slave in our case) to MODE 0 and Our host deriver(Master in our case) was  set to SPI mode 3. This setting started working.

We got the hint related to this from below link https://www.esp32.com/viewtopic.php?t=11578

Can you please confirm why this change fixes the issue ?

++++++++++++

**Comment by mantriyogesh** [comment]
Hello @anoop18pant 

There should be no change with the old and new C3. I assume both chipsets are with same rev.
Can you please get the logic analyser dump for the new C3?
This will ease us out to understand what is wrong.

Overall, in your case,
It is essentially important to get the basic SPI working at Host side (without hosted), if that works, you should observe the first SPI transaction from ESP to host. As you are already familiar with issue discussed in https://github.com/espressif/esp-hosted/issues/101#issuecomment-1043053188.  it should be easy to localize the host side user space SPI driver works or not. you can use the ESP-IDF SPI slave example to verify with Linux user space driver.

Can you please confirm the ESP-Hosted commits used for ESP and host? also what is the ESP-IDF release and commit being used?

Additionally, one input,
Can you please verify if ESP32-C3 <- [IDF example](https://github.com/espressif/esp-idf/tree/release/v4.3/examples/peripherals/spi_slave) -> ESP32-C3 works? This will help to understand if something is wrong with the ESP32-C3 you had bought.
