### ISSUE TITLE
telnet or ssh

### ISSUE THREAD

**Issue by micheledarold** [espressif/esp-hosted#124]
Hi, I have ESP32 with esp-hosted connected to Raspberry Pi 4B with SPI interface.
I can connect to a wifi network but I can't reach the board from a pc via telnet o ssh,
(the same are working via eth interface)

thank you

**Comment by MangeshMalusare** [comment]
Thanks for reporting the issue. Can you please run the following commands on Raspberry and share the output? Make sure to connect to AP before running these commands.

ifconfig -a
ping <ap>
ping <pc>
route -n
arp -n

**Comment by micheledarold** [comment]
Good morning sorry for my issue, the problem was related to my network configuration, the wifi network wasn't in the same network segment.
