### ISSUE TITLE
Official release scheduling

### ISSUE THREAD

**Issue by micheledarold** [espressif/esp-hosted#126]
Hi, the project is very interesting, there is a plan to make a official release of the application?

The actual branch could be considered stable?

Thank you

Michele

**Comment by mantriyogesh** [comment]
Hello @micheledarold 

The releases on project repo page are stable releases. Just keep in mind that you should note the git commit on which ESP binaries were created and use the same commit to build the host kernel module building.

Please do let us know if any confusion.

~ Yogesh

**Comment by mantriyogesh** [comment]
@micheledarold 

You can also test master commit. It is tested against our internal sanity testing suites.
Difference between release and master:
In case of release, ESP binary created could be directly flashed. If you use master, you need to build and flash ESP image.
Both ways are simple and explained in detail in documentation.

Just make sure, both places use same git commit

**Comment by mantriyogesh** [comment]
@micheledarold, There is First Genration release out last week.
Can we please close the issue if there are no further open questions?
