### ISSUE TITLE
Manage the device using NetworkManager

### ISSUE THREAD

**Issue by ChromaMaster** [espressif/esp-hosted#127]
Hi! 

Is there a way to fully manage the device using NetworkManager? I'd like to create a piece of software which controls the system's network using NetworkManager via D-Bus. However, when I tried to use the esp-hosted solution for this, I noticed that the device is not identified as a wireless device by NetworkManager. So I was wondering if there is a way to do this. 

Here is how I checked the device type in network manager:

1. First checking which device is which based on the `Interface` property
```
# dbus-send --system --print-reply   --dest=org.freedesktop.NetworkManager   
    /org/freedesktop/NetworkManager/Devices/3 \
    org.freedesktop.DBus.Properties.Get \
    string:"org.freedesktop.NetworkManager.Device" \
    string:"Interface"

method return time=1657106639.560455 sender=:1.5 -> destination=:1.27 serial=414 reply_serial=2
   variant       string "ethsta0"
```

2. Checking the `DeviceType` property of the device, it returns 1, which is `NM_DEVICE_TYPE_ETHERNET` according the [NetworkManager documentation](https://developer-old.gnome.org/NetworkManager/stable/nm-dbus-types.html#NMDeviceType)
```
# dbus-send --system --print-reply   --dest=org.freedesktop.NetworkManager \
    /org/freedesktop/NetworkManager/Devices/3 \
    org.freedesktop.DBus.Properties.Get \
    string:"org.freedesktop.NetworkManager.Device" \
    string:"DeviceType"

method return time=1657106648.384640 sender=:1.5 -> destination=:1.28 serial=415 reply_serial=2
   variant       uint32 1
```

It is the same for the `ethap0` interface

**Comment by MangeshMalusare** [comment]
Thank you for raising this issue. 

Network manager needs 802.11 interface, whereas ESP-Hosted presents 802.3 interface. Both ethsta0 and ethap0 are 802.3 interfaces. That's why network manager fails to detect them as wifi interfaces. This is expected behavior.

We will soon add support for 802.11 interface (standard wifi interface) which can be used with Network Manager. Please keep checking github for updates.

Thanks,
Mangesh

**Comment by mantriyogesh** [comment]
Hello @ChromaMaster,

This is to inform you update regarding the original issue you had raised.
With the latest release, cfg802.11 support is added. With that, one can directly configure using wpa_supplicant.

**Comment by ChromaMaster** [comment]
Awesome news @mantriyogesh. I'll be trying it these weeks!

I'll just close this issue and if any other issue related with the 802.11 support appears, I'll let you know!
