### ISSUE TITLE
Will ESP32-C5 be supported in the future?

### ISSUE THREAD

**Issue by modi12jin** [espressif/esp-hosted#136]
Sorry to bother you!  I wonder if there will be support for ESP32-C5 in the future?

**Comment by mantriyogesh** [comment]
Hello @modi12jin ,

[ESP32-C5](https://www.espressif.com/en/news/ESP32-C5) is definitely fascinating chipset, considering BLE 5.0 + dual-band support with Wi-Fi 6.

Considering so many chipsets already supported/ported, porting to any different chipset should be an easy, small task.
For example, to support S3, code related changes in this commit were very minimal: https://github.com/espressif/esp-hosted/commit/4688eacf152f294e257c1e5091af589dc9fb05f9 

For hosted point of view, It would be supported, once it is easily available in market.
