### ISSUE TITLE
 HCI scan errors when Using esp32C3 hosted mode

### ISSUE THREAD

**Issue by anoop18pant** [espressif/esp-hosted#138]
hi,

We are using ESP32C3 hosted mode we are observing one issue when we have a lot many BLE devices then we are observing the HCI device errors time outs etc....

The random errors are occurring.

Any help pointer will be appreciated.

**Comment by mantriyogesh** [comment]
Yes, we will surely look into the issue.
Can you please help to close other issues where you have received the solution?

Please send us the logs,
1. host
- dmesg
- btmon log while test running
- bluetoothctl log
2. esp
- firmware log

**Comment by TreeNewbeer** [comment]
I also met a related issue and I found that it always occurs in ble adv report. I think this problem is about the adv report flow control, the esp-idf has some configuration macros are related to here, but I have no time to varify that whether changes those configurations will fix it or not.

**Comment by TreeNewbeer** [comment]
![0eeac8985e5f52245ec0817c446c86c](https://user-images.githubusercontent.com/29987029/182080013-865c3e7f-95f7-47ef-ba30-e2217bb6d40f.png)

Those configuration macros I found are here. Hopefully it will make some sense.

**Comment by mantriyogesh** [comment]
Hello @anoop18pant ,
By any chance are you using hcitool? hcitool is deprecated for latest blueZ releases.
You can use 'bluetoothctl' instead.

Could you please provide ESP, Host Kern log, bluetoothctl and btmon log to understand the issue you faced?

**Comment by mantriyogesh** [comment]
Have you got it working @anoop18pant ?

**Comment by mantriyogesh** [comment]
Any updates @anoop18pant ?

**Comment by anoop18pant** [comment]
After changing the clock from 1 mhz to 20 mhz seems the issue is not occurring.

Though not sure about it

**Comment by mantriyogesh** [comment]
Great, thanks.

One possibility that, the data is not getting pushed fast within expected timers expected by BlueZ, because of slower frequency.
Can you please help closing the issue?

**Comment by anoop18pant** [comment]
After clock speed change not observing the change.
