### ISSUE TITLE
setup.md is missing

### ISSUE THREAD

**Issue by vuhailongkl97** [espressif/esp-hosted#153]
Dear authors,

I've checked your guideline, I saw that this page is missing many information for the setup (how to build, test). Please consider to fix it.

 
https://github.com/espressif/esp-hosted/blob/master/docs/setup.md

**Comment by mantriyogesh** [comment]
Can you please let us know what exact information you feel is missing?
We can try to make it better visible in that case.

**Comment by vuhailongkl97** [comment]
I didn't see any instruction about how to build with command lines, I think something like how to run `rpi_init.sh` which need to be added like previous version (before NG)

**Comment by mantriyogesh** [comment]
- [ ] Actually, we tried to make it simpler in this version.

- [ ] Can you please see below tabular setups folded

<img width="841" alt="Screenshot 2022-08-30 at 10 10 11" src="https://user-images.githubusercontent.com/67477199/187350938-e66bd649-8e38-413c-9335-48a729975816.png">

- [ ] Then unfold the option one by one.
<img width="747" alt="Screenshot 2022-08-30 at 10 12 33" src="https://user-images.githubusercontent.com/67477199/187350960-60f6f999-4a3b-4f9b-977c-cdaf5cdd9493.png">

- [ ] This way it can help get focus on only what transport combination you use.

- [ ] As you follow ahead, you would get the details of rpi_init.sh as well.

<img width="1035" alt="Screenshot 2022-08-30 at 10 23 12" src="https://user-images.githubusercontent.com/67477199/187352322-24a004ab-7b51-45e7-a1fd-b5a93c50ed74.png">


Hope this answers your question.

**Comment by vuhailongkl97** [comment]
@mantriyogesh I got it.
