### ISSUE TITLE
kernel 5 and NG

### ISSUE THREAD

**Issue by micheledarold** [espressif/esp-hosted#168]
Hi, what about kernel 5.x and NG version?
I have tried to compile but I got errors. It's supported?

Thank you

**Comment by MIPMHannes** [comment]
Yeah kernel 5.x is supported. I got it up and running on kernel version 5.15.61-v7l+. The issue might be something else.

**Comment by mantriyogesh** [comment]
Thank you. Are you still stuck or got it working?

**Comment by micheledarold** [comment]
Hi, is still not working, I can't send the trace of the error because I need to complete some other urgent tasks and I switch to old version of kernel and yocto.
By the way I'm using yocto Rocko (kernel 4.x) and the problem are with yocto Dunfell kernel 5.10

**Comment by mantriyogesh** [comment]
Any build logs would be much appreciated.

**Comment by mantriyogesh** [comment]
@micheledarold please do connect when you are able to work on 5.10 kernel again.
Kernel 5.10 tested with Raspberry Pi & it is working as expected..

**Comment by micheledarold** [comment]
Hi @mantriyogesh the problem was related to the Yocto recipe, the bluetooth was missing and so the kernel not work, now with the right setting everything is compiling
Referred also to #137 .
Thank you
