### ISSUE TITLE
write failed: Broken pipe

### ISSUE THREAD

**Issue by MrHaiCoder** [espressif/esp-hosted#201]
I am use esp_hosted_fg, use spi transfer；
test espsta mode，use iperf tcp test, often  occur  write failed: Broken pipe;
What causes this situation？
![image](https://user-images.githubusercontent.com/28109659/217470716-5986fa1c-791e-45b7-a364-d1bbd88d72ed.png)

**Comment by MrHaiCoder** [comment]
use esp32s3

**Comment by mantriyogesh** [comment]
Can't judge only from iperf log.
I suspect stream getting closed (due to.timeout or something)

Can you share:
1. Which MCU/Linux?
2. Logs at host, esp

**Comment by mantriyogesh** [comment]
Any errors popped up in either logs above will give some hint.

**Comment by MrHaiCoder** [comment]
> 在上面的任一日志中弹出的任何错误都会给出一些提示。
use linux4.9.4 version;
to save a pin,we donot use host reset esp32s3 pin, 
esp32s3 will sleep  wait a time，to sure host recv init event ;
detail log
[20230208-173146.log](https://github.com/espressif/esp-hosted/files/10684526/20230208-173146.log)

**Comment by mantriyogesh** [comment]
All logs are mixed up and cannot understand.
Still I checked, no noticeable error found in log.

Can you please open a new terminal and do
$ tail -F /var/log/kern.log
If you don't have /var/log/kern.log, you can use /var/log/messages.
Now, In the **same terminal**, get to connection up (test_2.out etc ... Till ping working) and run iperf there, to reproduce the issue.

Also please collect **esp side logs** at the same time.
- If you are flashing source code with idf.py, you can add 'monitor' in the command
- if you are flashing release binary, you can do minicom

**Comment by mantriyogesh** [comment]
Are you receiving `Received INIT event from ESP32 peripheral` when the issue occurs?
If yes, that hits that ESP is getting reset, we need to check ESP logs in that case.

**Comment by MrHaiCoder** [comment]
in Office environment test ，There will be iperf broken pipe on your side ?

**Comment by mantriyogesh** [comment]
Nope. It doesn't.
Please send us the above logs, we can definitely check if something is wrong or not.

**Comment by MrHaiCoder** [comment]
What does the kernel log mainly focus on? There is no such file in our system. The log mcu colleagues on the esp side are collecting data. I first used tcpdump to capture the data packets. You can use wireshark to view

192.168.0.1 is ethap0 ip

[target.zip](https://github.com/espressif/esp-hosted/files/10694449/target.zip)

**Comment by MrHaiCoder** [comment]
Hi，mantriyogesh，
In the space environment without other wifi ap, use iperf to conduct multiple tests for a long time, and there is no broken pipe

**Comment by mantriyogesh** [comment]
> What does the kernel log mainly focus on? There is no such file in our system. The log mcu colleagues on the esp side are collecting data. I first used tcpdump to capture the data packets. You can use wireshark to view
> 
> 192.168.0.1 is ethap0 ip
> 
> [target.zip](https://github.com/espressif/esp-hosted/files/10694449/target.zip)

Two parts for ESP-Hosted:
1. Host
- As you said, you are using Linux system, it must have some log, where kernel dumps the log. It could be either `/var/log/kern.log` or /var/log/messages`
Nothing works out, run `dmesg` to get current kernel log.
Our kernel driver will log some information onto kernel log (as it is running in kernel space).
- In addition, Get us the run log (commands you have fired and their output)

2. ESP
Get us ESP log
- If you are using firmware release binary you can get ESP side log with minicom.
- If you are building and flashing manually with code, even adding 'monitor' in existing idf.py command will get you ESP side log. e.g. `idf.py flash monitor`

---

> Hi，mantriyogesh，
> In the space environment without other wifi ap, use iperf to conduct multiple tests for a long time, and there is no broken pipe

Good to see you are trying it with other AP (to verify if it is AP problem itself).

BTW, which iperf version you are using?

**Comment by mantriyogesh** [comment]
By the time I will check you iperf tcp wireshark also. I am no expert in TCP, but as I understand, TCP re-transmission and error control is part of TCP protocol.

**Comment by MrHaiCoder** [comment]
use iperf2.0.8  test

**Comment by mantriyogesh** [comment]
Can you please send `ifconfig -a`?

Also, I see no FIN in the log.
There are too many factors affecting the OOO or duplicate ACKs like line of sight, distance, radio conditions, noisy environment (say microwave or Bluetooth device is nearby the AP or station etc, etc).

I would suggest you to try with with another channel number and different bandwidth say 40MHz for softAP and re-assess the connection.

**Comment by mantriyogesh** [comment]
Alternatively, to assess is to use these two (ESP-SoftAP and AP) in quieter environment and have same (exactly same, like channel, BW, 2.4GHz etc) radio configs (switch on one at a time) and compare if issue observed.
Do let us know the finding, we can know how to progress then.

**Comment by MrHaiCoder** [comment]
![image](https://user-images.githubusercontent.com/28109659/217805481-b64b53c7-a4a3-4694-8a6a-1fd4104f7129.png)
./test_2.out  softap_start 
ifconfig ethap0 192.168.0.1 netmask 255.255.255.0
route add default gw 192.168.0.1 dev ethap0
./busybox udhcpd udhcpd.conf &

**Comment by MrHaiCoder** [comment]
![image](https://user-images.githubusercontent.com/28109659/217805481-b64b53c7-a4a3-4694-8a6a-1fd4104f7129.png)
./test_2.out  softap_start 
ifconfig ethap0 192.168.0.1 netmask 255.255.255.0
route add default gw 192.168.0.1 dev ethap0
./busybox udhcpd udhcpd.conf &

**Comment by mantriyogesh** [comment]
ethap0 doesn't show the dropped packets.

Anyway, share the logs as mentioned in ealier comment to verify is something wrong at ESP-Hosted.

**Comment by MrHaiCoder** [comment]
> ethap0 doesn't show the dropped packets.
> 
> Anyway, share the logs as mentioned in ealier comment to verify is something wrong at ESP-Hosted.

There is no problem with the version of iperf2.0.9. It should be the version of iperf；
 wifi/iperf/main/iperf_example_main.c also no this problem.

**Comment by mantriyogesh** [comment]
https://github.com/espressif/esp-hosted/issues/201#issuecomment-1424031200

Please change (improve) radio conditions & espap0 radio configs as discussed earlier.
If you see the code, the ESP-Hosted just relays the packet without even processing it.

**Comment by MrHaiCoder** [comment]
> [#201 (comment)](https://github.com/espressif/esp-hosted/issues/201#issuecomment-1424031200)
> 
> Please change (improve) radio conditions & espap0 radio configs as discussed earlier. If you see the code, the ESP-Hosted just relays the packet without even processing it.

Yeah,I understand. Linux host code is really only used to add data headers and transmit them.

I've encountered another problem on my side. It is also linux 4.9+esp32s3, Fg solution, linux is running on dual core mips chip. The esp32s3 acts as an ap, the pc goes to connect to the ap and uses tcp to transfer data, after running for about 5min, the network latency becomes very high.
I added the log to read the value of tx_pending after atomic_inc(&tx_pending) and also added the log to read the value of tx_pending after atomic_dec(&tx_pending), which is a producer-consumer relationship, and I found that the producer is very slow at the back, i.e. the network is not sending out. But I turned off a cpu core in going to run the network, and there was no network latency getting higher

**Comment by MrHaiCoder** [comment]
![image](https://user-images.githubusercontent.com/28109659/221419393-a6867211-1495-4560-aa02-a86542596387.png)
See this image, should this { be moved to the top? Because tx_pending is used to control the
PRIO_Q_OTHER queue

**Comment by mantriyogesh** [comment]
Okay, let me review the code in the morning, get back to you..

**Comment by mantriyogesh** [comment]
Btw thank you for checking this issue and all observations.
If any problem, definitely, we should address.

**Comment by MrHaiCoder** [comment]
> Btw thank you for checking this issue and all observations. If any problem, definitely, we should address.

![image](https://user-images.githubusercontent.com/28109659/221456775-2abb1156-37cc-4c9b-a814-661786b49365.png)
![image](https://user-images.githubusercontent.com/28109659/221456865-6137e308-5751-48e7-8ec1-9d2d5b7206cc.png)


![image](https://user-images.githubusercontent.com/28109659/221456561-2bb41fba-fbbc-4409-860b-0fa775d2a427.png)

CPU production package becomes very slow.

**Comment by mantriyogesh** [comment]
Actually, producer can wait if the current packets are not fully processed.

![Screenshot 2023-02-27 at 10 06 42 AM](https://user-images.githubusercontent.com/67477199/221456673-02e017c8-69d9-48de-a80f-61858cb55467.png)

**Comment by mantriyogesh** [comment]
Okay, let me check your last post, it seems I also added the post same time.

**Comment by MrHaiCoder** [comment]
> Actually, producer can wait if the current packets are not fully processed.
> 
> ![Screenshot 2023-02-27 at 10 06 42 AM](https://user-images.githubusercontent.com/67477199/221456673-02e017c8-69d9-48de-a80f-61858cb55467.png)

![image](https://user-images.githubusercontent.com/28109659/221461807-f00b0a79-e9b2-41d6-9ad5-fe7c6fe9a8c2.png)

**Comment by mantriyogesh** [comment]
![Screenshot 2023-02-27 at 10 34 42 AM](https://user-images.githubusercontent.com/67477199/221460015-5b3748ce-2824-46ee-a0b9-c854376d80d7.jpg)

We should only decrement the tx_pending when we have actually processed the packet.
If the tx_skb is NULL for PRIO_Q_OTHERS, we simply come out, because there is no packet pending in the queue.

Can you please go through below trial list and review and/or test:
[TRY 1]
We can check the tx_pending first and if `tx_pending` is non zero, try to fetch the tx_skb out.
If `tx_pending` is zero, we safely assume, there is no packet pending for PRIO_Q_OTHERS. 
```c
283     if (trans_ready) {
284         if (data_path) {
285             tx_skb = skb_dequeue(&spi_context.tx_q[PRIO_Q_SERIAL]);
286             if (!tx_skb)
287                 tx_skb = skb_dequeue(&spi_context.tx_q[PRIO_Q_BT]);
288             if (!tx_skb) {
289                 if (atomic_read(&tx_pending)) {
290                     tx_skb = skb_dequeue(&spi_context.tx_q[PRIO_Q_OTHERS]);
291                     if (tx_skb) {
292                         atomic_dec(&tx_pending);
293
294                         if (atomic_read(&tx_pending) < TX_RESUME_THRESHOLD) {
295                             esp_tx_resume();
296 #if TEST_RAW_TP
297                             esp_raw_tp_queue_resume();
298 #endif
299                         }
300                     }
301                 }
302             }
303         }
```

[Try 2] From the above snippet, **remove** part
```c
294                         if (atomic_read(&tx_pending) < TX_RESUME_THRESHOLD) {
295                             esp_tx_resume();
296 #if TEST_RAW_TP
297                             esp_raw_tp_queue_resume();
298 #endif
299                         }
```
and add it at just before
```
360     mutex_unlock(&spi_lock);
```

[TRY 3]
As I said in earlier post, if we out-running the capacity. we can find out if we are hitting 
![Screenshot 2023-02-27 at 10 06 42 AM](https://user-images.githubusercontent.com/67477199/221464726-60c516e3-8117-48b2-a50a-032baab8917e.png)
Please revert all TRY 1 / 2 changes so that we do not complicate the findings.

[TRY 4]
As from your earlier observation for SMP you are facing the issue and not facing issue when it is uniprocessor.
Scheduling problems?

I had thought if we can replace `mutex_lock(&spi_lock); & mutex_unlock(&spi_lock);` with spinlock like `spin_lock_irqsave & spin_unlock_irqrestore` or down_interruptible semaphore.
Please revert all TRY 1 / 2 changes so that we do not complicate the findings.

**Comment by MrHaiCoder** [comment]
I will try it as soon as possible. This problem will not occur when using a core CPU.
BTW, why is there no lock at the place where you join the queue?

**Comment by mantriyogesh** [comment]
> why is there no lock at the place where you join the queue?

Can you please point me the exact code line(s)?

**Comment by MrHaiCoder** [comment]
> > why is there no lock at the place where you join the queue?
> 
> Can you please point me the exact code line(s)?

![image](https://user-images.githubusercontent.com/28109659/221475494-e90175f2-f1ac-48d9-be5c-99e6101421dc.png)

**Comment by mantriyogesh** [comment]
I am not sure what are you pointing me at.
Anyway, Queues are by default protected. All operations are expected to be serialised when we do operations over queue.
So we do not want any additional locks for queues.

**Comment by mantriyogesh** [comment]
But then what are you running on the Linux in user space?
Is there any packet sent from Linux to ESP?
Can you share the complete patch & logs together?

tx pause happens when the packets are flowing more than capacity, to hold the queue for any further inputs.
tx resume happens when there is sufficient room to hold new packets (capacity is available)

I cannot understand from your last images.

For small number of packets, queue will not be paused & resumed, as it will be well within the capacity.
tx_pending will increment after placing item into tx_queue. Similarly decrement once it is dequeued for processing.

So it is better to share the code patch and logs at the same time to derive correct conclusion (and for shared understanding)

**Comment by mantriyogesh** [comment]
Packet will only be sent if user space sends something (say iperf traffic or some packet by higher layer like arp, DHCP etc).
If nothing is being sent from user-space, nothing the kernel module will do.
It will only act if user space have sent something.

**Comment by MrHaiCoder** [comment]
[src_log.tar.gz](https://github.com/espressif/esp-hosted/files/10837127/src_log.tar.gz)

Above is the test program and the corresponding kernel driver log, the user space program is sending network packets without interruption. In the log you can focus on the time before and after the empty line

**Comment by mantriyogesh** [comment]
tcp_server.c -> What am I expected to understand from this file?

I need the code change you have with ESP-Hosted repo.
You can make patch of it.

also please capture the running log (commands you fire in user-space and output of them)
Also get ESP log, just to be sure nothing else is going wrong underneath.

**Comment by mantriyogesh** [comment]
Also please help point me the problem in the log may be using timestamp or line number

**Comment by MrHaiCoder** [comment]
tcp_server.c is my test demo，what I want to say is that this program does not stop sending data.

![image](https://user-images.githubusercontent.com/28109659/221505990-91eadbf9-6b99-4d8c-ab4a-b4a5e2e0400b.png)

**Comment by mantriyogesh** [comment]
https://github.com/espressif/esp-hosted/issues/201#issuecomment-1445848967

**Comment by MrHaiCoder** [comment]
I need another colleague to help me with the esp32 log, but I can confirm that the data is being sent through the spi very quickly. Is it convenient to set up a test environment on your side?

**Comment by mantriyogesh** [comment]
I can, but it might take some time to test, I am in between priority work.
As you had been in problem since long, I am trying to respond quickly.

Can you send the ESP-Hosted code change patch and tcp client side logs?

**Comment by MrHaiCoder** [comment]
[patch.zip](https://github.com/espressif/esp-hosted/files/10837486/patch.zip)
NetAssist can used tcp client

**Comment by MrHaiCoder** [comment]
> I can, but it might take some time to test, I am in between priority work. As you had been in problem since long, I am trying to respond quickly.
> 
> Can you send the ESP-Hosted code change patch and tcp client side logs?

Please support as soon as possible, thank you very much!

**Comment by mantriyogesh** [comment]
Yes, Anyway, I will test with iperf2, when I reproduce this issue.
Is that okay for you?

I might take some time to test this.

**Comment by MrHaiCoder** [comment]
If you can use iperf, it is recommended that you run the ping program every other time and check the ttl;
Because my git repository no longer contains the previous. git hidden file, it is not convenient to generate a patch. I just add print to the two functions without logical modification

**Comment by MrHaiCoder** [comment]
If you are ready to test, it is recommended to use only two cpu cores for verification

**Comment by mantriyogesh** [comment]
I will be able to do this tomorrow.
Apologies for the delay..

**Comment by mantriyogesh** [comment]
If I add cs_change for esp32s3 on Raspberry Pi 4, the init/bootup event is also not received.
It is dependent on the host as said earlier, please **remove** it if things work with your host.

**Comment by mantriyogesh** [comment]
[2023.03.92_FG_NotReproduced_broken_pipe.tgz](https://github.com/espressif/esp-hosted/files/10870853/2023.03.92_FG_NotReproduced_broken_pipe.tgz)

Broken pipe not seen,
Also the traffic did not stuck in between for me (3/4 sec delay kind of issue for tx process)
Tried both, with Rx & Tx. (Tx makes more sense, still tried Rx as well)

**Comment by MrHaiCoder** [comment]
Because without this code （trans.cs_change = 1）, the host can't get the mac by calling the command,   
./test.out set_sta_mac_addr
so add

**Comment by MrHaiCoder** [comment]
Have you matched the wifi antenna of the Raspberry Pi you are using?
The high ping ttl latency from previous feedback may be related to the esp32s3, which our colleague added to print. Then after removing host and esp32s3 newly added debug logs.
We then tested inside the wireless shield box, the bandwidth can be up to 15Mbps, but then inside the office congested wifi channel, the bandwidth is very low, as follows.

![image](https://user-images.githubusercontent.com/28109659/222715093-18879879-219e-43a9-8419-9adbfcc9adac.png)

Can you provide any suggestions on how to improve wifi bandwidth stability?

**Comment by mantriyogesh** [comment]
Anyway It should not reduce to ZERO.
Can you check the routes and ifconfig if traffic routed incorrect IP?

Regarding Wi-Fi stability, I also test in office environment only, where signals are crowded, the effect will be seen with fluctuations, not dead zero.
Can you try another AP, with automatic channel selection and bandwidth to HT40 from HT20?

I have not done any changes to RF. (just bare metal)

**Comment by mantriyogesh** [comment]
![16778470133136413629740537094585](https://user-images.githubusercontent.com/67477199/222722025-e9bd07a0-2f7b-44b4-a858-57e5a1f1a2f0.jpg)

**Comment by mantriyogesh** [comment]
Can you also try on spi mode 3 at both ESP & RPi

**Comment by MrHaiCoder** [comment]
Thank you very much for trying!
I don't have a Raspberry Pi board, but what you said I will try。

Here is my network configuration, because our product has fewer resources for cost, the choice is udhcpd and his configuration as a dhcp service.

ifconfig ethap0 192.168.0.1 netmask 255.255.255.0 &&  route add default gw 192.168.0.1 dev ethap0 && ./busybox udhcpd udhcpd.conf & 
[udhcpd.zip](https://github.com/espressif/esp-hosted/files/10882550/udhcpd.zip)

**Comment by mantriyogesh** [comment]
I can't verify the udhcpd configs as such. But if you can get the ip address, should be fine.

It is still puzzling me whay I could go 15mbps  and other place going down to 0.
Can you help to figure out what could be different?
Hardwares used like specific chipset or soc having issue/software like low ram or cpu or kernel or linux change/ quality or length of jumper wires used/ power cables/power adapters/ specific place in office/debug prints / change in tools used for testing

**Comment by mantriyogesh** [comment]
$ ifconfig -a
$ route -n

**Comment by mantriyogesh** [comment]
Can you capture wifi sniffer logs ?
May give some hint.

**Comment by MrHaiCoder** [comment]
There are plenty of 2.4G wifi cameras in the office, tested on the negative ground floor without wifi interference with the office, using the same hardware and firmware program. 
esp and host are on the same pcb, not convenient to use dupont wire to replace the device
I can   capture wifi sniffer logs .  Available next Monday

**Comment by mantriyogesh** [comment]
Carrie other logs as well at the same time when you test

**Comment by mantriyogesh** [comment]
Were you able to check on this?

**Comment by mantriyogesh** [comment]
Any observations further?

**Comment by mantriyogesh** [comment]
Oh okay.
Thanks for the update.
If no more action, we can close issue.
