### ISSUE TITLE
Binaries version 0.3 missing at release tab

### ISSUE THREAD

**Issue by seahcj** [espressif/esp-hosted#21]
In [SDIO Setup Guide](https://github.com/espressif/esp-hosted/blob/master/docs/Linux_based_host/SDIO_setup.md), it is referring to binaries at 'release' tab.

`esptool.py -p <serial_port> -b 960000 --before default_reset --after hard_reset write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x8000 partition-table_sdio_v0.3.bin 0x1000 bootloader_sdio_v0.3.bin 0x10000 esp_hosted_firmware_sdio_v0.3.bin
`
The binaries version is 0.3, but the release tab has only version 0.1, and 0.2.

Please kindly take a look. thanks.

**Comment by MangeshMalusare** [comment]
Thanks for your query. Release 0.3 will be made available at the earliest. Meanwhile please use release 0.2 version binaries.

**Comment by seahcj** [comment]
thanks
