### ISSUE TITLE
If checksums are enabled is there any retry behavior, or are failured packets just dropped?

### ISSUE THREAD

**Issue by mjdietzx** [espressif/esp-hosted#219]
I can't find any retry behavior in the code. I would've expected quick retries if checksums failed. But it seems packets might be just dropped?

What are the reasons to enable checksums (I am using FG with esp32 module and linux host sdio master). I know TCP has checksums but i believe errors would manifest in http timeouts in my case, and this is slow/adds latency. But I am wondering if i would get any benefit from enabling checksums at esp-hosted/sdio layer

Can anybody explain the pros/cons of enabling/disabling checksums? Thank you

**Comment by mantriyogesh** [comment]
There is no retransmission or any other algorithm if the checksum is failed.
Checksums are only way to drop packet if the checksum verification fails.

This ensures only supported packets enter the system. If any packet with incorrect data like say payload length  or anything wrong and still gone ahead with processing, can lead to unexpected faults.

This is safeguard for two things:
1. To identify timing issues in initial setup 
2. To allow only valid packet enter system, else drop
