### ISSUE TITLE
SDIO support for MCU Host

### ISSUE THREAD

**Issue by seahcj** [espressif/esp-hosted#22]
May i know is there any plan to support SDIO connection between MCU host and ESP32? for esp-hosted solution.

**Comment by MangeshMalusare** [comment]
Thanks for your query. 

We are considering adding support for SDIO connection between MCU host and ESP32.
But there are no immediate plans to implement this.

**Comment by ameyinamdar** [comment]
The ESP32 side support is completely ready and is available in source format. This will not change from host to host. MCU side SDIO support is very specific to host MCU used and you can implement this based on specific MCU you plan to use. In future we will provide support for some standard MCU that has SDIO interface available.

**Comment by seahcj** [comment]
Noted. Thanks for the information
