### ISSUE TITLE
Strong emission when using WROOM32-E module

### ISSUE THREAD

**Issue by franziskanerda** [espressif/esp-hosted#227]
Sorry for interrupting you again. I am using this firmware with an WROOM32-E module:

[2023.02.23_NG_SDIOOnly_ClassicBT_custom_config.tgz](https://github.com/espressif/esp-hosted/files/10814778/2023.02.23_NG_SDIOOnly_ClassicBT_custom_config.tgz)

from the GitHub task

https://github.com/espressif/esp-hosted/issues/206

Unfortunately, it looks like the ESP module generates a lot of emission during the EMC test. At which drive strength are the pads running? Is there a possibility in the driver to change the drive strength of the following pads used for the SDIO interface (IO2, IO4, IO12, IO13, IO14 and IO15)? If this would work, I would like to repeat the test of the noise emission afterwards.

Thank you very much for your help!

**Comment by mantriyogesh** [comment]
hello @franziskanerda 
Sorry we did not test this.

But there are some APIs from ESP-IDF to check the drive strength.
We have not altered the defaults as such.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/gpio.html#_CPPv425gpio_get_drive_capability10gpio_num_tP16gpio_drive_cap_t
If you need we will create firmware with prints of them.

**Comment by franziskanerda** [comment]
Thank you. And thank you for publishing the source code of NG version. For that reason, I will close this task now.
