### ISSUE TITLE
The ESP32 uses the esp-hosted SDK as the WiFi NIC for the SPI communication. In addition to the function of SPI wifi network card, does it support Bluetooth?

### ISSUE THREAD

**Issue by JS-Ye** [espressif/esp-hosted#233]
### ESP chip/Product Platform:

- ESP chip:  ESP32-WROOM-32E
- Product Platform:  https://github.com/espressif/esp-hosted

### The ESP32 uses the esp-hosted SDK as the WiFi NIC for the SPI communication. In addition to the function of SPI wifi network card, does it support Bluetooth? If Bluetooth is supported, how should I add Bluetooth?

Bluetooth needs to achieve the following two functions:

1. Customize the 128bit service UUID, receive feature UUID, and send UUID.

2. After entering the data transmission mode, ESP32 acts as the Bluetooth slave, and APP acts as the host to send data to ESP32.

**Comment by mantriyogesh** [comment]
Hello @JS-Ye 

Can you please let us know the host used?
Linux /MCU, kernel version?

**Comment by zhlftest** [comment]
hello @mantriyogesh the host is linux ,But they didn't use the device tree

**Comment by mantriyogesh** [comment]
Yes Bluetooth and Wi-Fi are both supported using ESP-Hosted (By default this is enabled, if needed, you can configure only bluetooth or only Wi-Fi ).

Follow the documentation and video at https://youtu.be/g14aEjnjRLw for bluetooth related questions.

**Comment by mantriyogesh** [comment]
Hello @zhlftest 

Is the Bluetooth LE or BR/EDR?

> Customize the 128bit service UUID, receive feature UUID, and send UUID. 

Are you talking about GATT service?

**Comment by JS-Ye** [comment]
Hello @mantriyogesh  
   
I wonder if you can change 128bitUUID by adding an AT instruction to esp-hosted.  
>Customize the 128bit service UUID, receive feature UUID, and send UUID.

**Comment by mantriyogesh** [comment]
ESP-Hosted doesn't understand AT commands as such, unless you have something on top as your own AT interpreter. I am still trying to understand, how AT is relevant.

**Comment by mantriyogesh** [comment]
just to clarify .. BT controller is not the one that supports AT as such.
AT commands usually work on top of RFCOMM and is a data for controller i.e. controller doesn't have any special or separate handling for AT commands

RFCOMM layer will reach till stack which is still at host.
From host to controller HCI communication till bluetooth controller.
How do you communicate tith BlueZ stack, is upto you.

**Comment by mantriyogesh** [comment]
i hope the answers have clarified your question.
Can we close this thread?

**Comment by JS-Ye** [comment]
Ok, thank you for your support, this problem can be turned off.
