### ISSUE TITLE
"espsta0 " unable to set tx power,esp32c3

### ISSUE THREAD

**Issue by renyeguo** [espressif/esp-hosted#235]
"iwconfig espsta0 txpower 30”
Error for wireless request "Set Tx Power" (8B26) :
SET failed on device espsta0 ; Operation not supported.

**Comment by kapilkedawat** [comment]
Support for setting transmit power is available now.
Please use `iw dev espsta0 set txpower limit 2000`  in with latest code.

**Comment by renyeguo** [comment]
well, I pulled the latest esp_host_ng code, However, I still use "esp-hosted -NG Release 1.0.2" for the esp side firmware. Now when I run "iw dev espsta0 set txpower limit 2000", the following error occurs:

[789.802811] [0] esp32_spi_ng:wait_and_decode_cmd_resp: Command[16] timed out

[789.810280] [0] esp32_spi_ng:cmd_set_tx_power: esp32: wait_and_decode_cmd_resp(priv, cmd_node) failure, ret: -22

command failed: Invalid argument (-22)

Check whether the esp side firmware needs to be updated and whether a version newer than ESP-Hosted-NG Release 1.0.2 is available，thanks

**Comment by renyeguo** [comment]
@kapilkedawat

**Comment by kapilkedawat** [comment]
@renyeguo please compile the new firmware. Changes are both in host driver and firmware.

**Comment by renyeguo** [comment]
@kapilkedawat Ok, I got it, now you are the one to open source the source code of ESP-hosted-ng. Now my network is not in good condition, and it is very slow for me to build a new ESP-IDF project. Could you please provide the compiled firmware of your esp side, I want to verify this problem quickly

**Comment by renyeguo** [comment]
![image](https://github.com/espressif/esp-hosted/assets/52553703/d557f394-31ab-441e-bbe1-56cf47cc7c28)

**Comment by kapilkedawat** [comment]
Please try with attached firmware.
[firmware.zip](https://github.com/espressif/esp-hosted/files/11673109/firmware.zip)

**Comment by renyeguo** [comment]
thank u

**Comment by kapilkedawat** [comment]
@mantriyogesh this support is available now, please close this issue.
