### ISSUE TITLE
Change country wifi specifications

### ISSUE THREAD

**Issue by jcomas** [espressif/esp-hosted#247]
I'm testing ESP-Hosted firmware for Linux. It seems that ESP-Hosted only contains global firwmare and you can't specify country code Europe to use channel 13, for example:
iw reg set DE
I can only write:
iw reg set 00

**Comment by kapilkedawat** [comment]
Hi @jcomas , thanks for the input and trying out esp-hosted solution. We will add this support.

**Comment by kapilkedawat** [comment]
@jcomas Please try with latest firmware and host. Do note that you need to compile new firmware for this.

**Comment by kapilkedawat** [comment]
@mantriyogesh this is done, please close this.
