### ISSUE TITLE
esp_hosted_config.proto is missing a license header.

### ISSUE THREAD

**Issue by iabdalkader** [espressif/esp-hosted#249]
Can you please add a license header to the file [esp_hosted_config.proto](https://github.com/espressif/esp-hosted/blob/master/esp_hosted_fg/common/proto/esp_hosted_config.proto) or clarify which license applies to it, and to the files generated using that file ? Thanks!

**Comment by mantriyogesh** [comment]
Hello @iabdalkader ,

The license header added in the proto file as part of commit https://github.com/espressif/esp-hosted/commit/003bc3fd1ac7b3a27c7c20fb6b59dfa2a485a136 .

Please help closing issue if no further action needed.
