### ISSUE TITLE
About ESP Tx power

### ISSUE THREAD

**Issue by LuciaferKelvin** [espressif/esp-hosted#268]
Is the esp hosted firmware automatic  change the tx power in working?
If I want to test different kinds of antenna ?
What is the best way to get different kinds of antenna tx power and receive sensitivity？
I want to get some data to compare different kinds of  antenna .

**Comment by mantriyogesh** [comment]
NG also supports power tuning from host from wpa_supplicant/cfg80211:

https://github.com/espressif/esp-hosted/blob/master/esp_hosted_ng/host/esp_cmd.c#L249-L253

**Comment by LuciaferKelvin** [comment]
But the host just could set set max tx power， if I set the max tx power， the esp will using that power level？

**Comment by LuciaferKelvin** [comment]
for example ，If I set the 15dbm max Tx power,  Will the esp rearch the tx power level?

**Comment by kapilkedawat** [comment]
> for example ，If I set the 15dbm max Tx power, Will the esp actual tx power reach it value and keep it?

@LuciaferKelvin it will the maximum value of transmit power that will be used during transmission subjected to regulatory restrictions.

**Comment by mantriyogesh** [comment]
can we close this?
