### ISSUE TITLE
Fail to creat GATT server

### ISSUE THREAD

**Issue by linchanghe123** [espressif/esp-hosted#272]
Hello @mantriyogesh
According to the guidance of docs/bluetooth.md, the following error was reported when using the bluetoothctl tool to create gatt servers. What is the reason for this?
![image](https://github.com/espressif/esp-hosted/assets/15261661/b8a1e1a2-a0aa-461c-8c06-f4b1186979ae)
![image](https://github.com/espressif/esp-hosted/assets/15261661/6ae55dcd-fe85-400d-aa42-2f703c4bd458)
![image](https://github.com/espressif/esp-hosted/assets/15261661/61791696-e815-43de-9e9c-6da6e67fe1a4)

thanks

**Comment by mantriyogesh** [comment]
I see that HCIconfig is down.
I think the ESP-Hosted is not setup correctly.

Can you please check if raw throughput test is working fine first?

**Comment by mantriyogesh** [comment]
Dmesg and esp logs can also point the issues

**Comment by mantriyogesh** [comment]
Hello @linchanghe123 ,

Can you please let us know the above logs, if issue is still faced?

**Comment by linchanghe123** [comment]
We have implemented the connection function by calling the functions of the bluez open-source library ourselves. Thank you!
