### ISSUE TITLE
Should the rpc api be used in the features branch for ports?

### ISSUE THREAD

**Issue by claydonkey** [espressif/esp-hosted#280]
@mantriyogesh 

I am very confused about the mechanics in the new features branch. It does indeed look cleaner and ultimately I'm sure it's more manageable but I have my knickers in a twist here:

I have a compile without errors as a starting point with most elements of the new hosted branch in place but I have been confusing myself by mixing in older elements from the patched version

 I am unable and not really willing to get a esp32<>esp32 setup running - to be honest I don't really want to setup up the whole ide/debugging for the esp32 host/slave scenario. So...

**esp_hosted_host_init**

including esp_hosted_up_sem + transport_up_sem << are these a thing?

```C
//ESP_SYSTEM_INIT_FN(esp_hosted_host_init, BIT(0), 120)
static void __attribute__((constructor)) esp_hosted_host_init(void)
```
?"!"£$

Are you using the rpc wrapper for features branch + for future ports of esp-hosted slave?
I am attempting to init + start the wifi which used to be managed under  wifi_init. Should I now call esp_hosted_host_init at some point and allow the rpc calls to take care of calls?

Talking a load of twoddle here but it does indicate my level of confusion

~~I'm sorry this is late in the week...
So, the features branch is compiling for stm32 but the hook esp_wifi_init is left as NULL
In the previous versions there was the wifi_drv.c file which called the test_wifi_..... now rpc_wifi... (I believe) functions to rpc's in addition to creating the esp_hosted_up_sem.~~

~~I understand on updating the features branch much of the component code was offloaded to the esp-idf functions but how does one hook another host into the process chain? rpc_api.c has disappeared and I am a bit lost as to how to proceed.~~

Before:
```C
void esp_hosted_up_cb(void)
{
	if (esp_hosted_up_sem)
		g_h.funcs->_h_post_semaphore_from_isr(esp_hosted_up_sem);
}

esp_err_t esp_wifi_init(const wifi_init_config_t *config)
{
	ESP_LOGV(TAG, "Trigger Wifi init");
    esp_hosted_up_sem = g_h.funcs->_h_create_semaphore(1);
	if (!esp_hosted_up_sem)
		printf("Unable to create sem %s:%u\n", __func__, __LINE__);
	g_h.funcs->_h_get_semaphore(esp_hosted_up_sem, portMAX_DELAY);

	ESP_ERROR_CHECK(esp_hosted_init(esp_hosted_up_cb));
	g_h.funcs->_h_get_semaphore(esp_hosted_up_sem, portMAX_DELAY);

#if 0//TEST_RAW_TP
	/* Just block the app main so that wifi will be stopped and only raw tp will be running */
	g_h.funcs->_h_get_semaphore(esp_hosted_up_sem, portMAX_DELAY);
#endif
	/*g_h.funcs->_h_get_semaphore(esp_hosted_up_sem, portMAX_DELAY); //Wait until slave is ready*/
	return test_wifi_init(config);
}

int test_wifi_init(const wifi_init_config_t *arg)
{
	/* implemented synchronous */
	ctrl_cmd_t req = RPC_DEFAULT_REQ();
	ctrl_cmd_t *resp = NULL;

	if (!arg)
		return FAILURE;

	g_h.funcs->_h_memcpy(&req.u.wifi_init_config, (void*)arg, sizeof(wifi_init_config_t));
	resp = wifi_init(req);

	return rpc_rsp_callback(resp);
}
```

**Comment by mantriyogesh** [comment]
yes, you can bypass esp-wifi-remote (and middle layer) if you think that is better.
Nevertheless, I took this as feedback and would improve the new branch for non esp MCU as well (with optional hooks wherever possible)..

**Comment by claydonkey** [comment]
@mantriyogesh 
Thanks again for this.
As you can gather I have turned to the rpc version. It is nice and clean and I'm almost there...
Just the reset on the Slave... #283

**Comment by mantriyogesh** [comment]
Lost the track on this. Anything blocked on @claydonkey ?
