### ISSUE TITLE
esp_sdio驱动加载失败，

### ISSUE THREAD

**Issue by liuyuaaa** [espressif/esp-hosted#291]
![image](https://github.com/espressif/esp-hosted/assets/74517176/0bd2d4c9-da40-4b49-9328-6cabe301c2d9)
![image](https://github.com/espressif/esp-hosted/assets/74517176/7a00b1ad-ef3e-46cc-bacd-f3c00727c21d)
使用树莓派3b与esp32相连接，./rpi_init.sh sdio执行后，未见到主设备号为221的字符设备生成
![0e71fbe7c1e6df83ead534891fb01d0](https://github.com/espressif/esp-hosted/assets/74517176/35756328-87cd-43e9-87a9-04c01abcd0e8)

**Comment by mantriyogesh** [comment]
Hello @liuyuaaa 

Thank you for the logs and setup image.
I think the wires are very long still.

Can you please get ESP logs, Host logs (dmesg, rpi_init.sh command run and output) in textual form?
Can you please also try 1bit sdio mode : https://github.com/espressif/esp-hosted/issues/269#issuecomment-1780697351, which should face less signal integrity issues?

**Comment by liuyuaaa** [comment]
这是ESP32的logs, 还有Host的logs (dmesg, rpi_init.sh）
[dmesg.log](https://github.com/espressif/esp-hosted/files/13507673/dmesg.log)
[ESP.log](https://github.com/espressif/esp-hosted/files/13507674/ESP.log)
[rpi_init.sh.log](https://github.com/espressif/esp-hosted/files/13507675/rpi_init.sh.log)

**Comment by liuyuaaa** [comment]
我尝试了1bit sdio模式，在树莓派/boot/config.txt文件添加了dtoverlay=sdio,poll_once=off,bus_width=1，现象是一样的，还需要修改其他的吗

**Comment by mantriyogesh** [comment]
I assume this is 4 bit mode logs you had shared.
Checked the logs. Logs as such are clean.

The jumper wire length is very big, need to make them smaller, else you would face such issues.

![Screenshot 2023-11-30 at 10 37 39 AM](https://github.com/espressif/esp-hosted/assets/67477199/e772b85d-7c51-426e-b123-9d3171e54f5e)

**Comment by liuyuaaa** [comment]
我们尝试了以下几点：
1，我们又重新飞线，缩短至3cm，上拉电阻为20k
2，Linux host 版本切换到了0.0.5
3，sdio的时钟频率已降到了5MHz

 rpi_init.sh执行后，结果没有变化。

**Comment by liuyuaaa** [comment]
我们测量发现data2管脚（esp32 gpio12）的电压为2.4v，其他data管脚为3.3v，这一点有没有影响。
![image](https://github.com/espressif/esp-hosted/assets/74517176/07d9427b-3a27-4325-b722-323a4611204f)
是不是因为内部下拉影响了这个管脚

**Comment by mantriyogesh** [comment]
Worth checking:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/sd_pullup_requirements.html

**Comment by liuyuaaa** [comment]
感谢，问题解决了。
我们测试了sdio的1 bit mode，ESP32是可以正常工作的。这样可以看出data2和data3出问题了，后来发现data2管脚接错了，重新焊接测试下就行了。

**Comment by mantriyogesh** [comment]
@liuyuaaa Can we close this issue?
