### ISSUE TITLE
Error in rpi_init.sh

### ISSUE THREAD

**Issue by NikolayTsvetkovv** [espressif/esp-hosted#328]
When you set ESP_SLAVE_CHIPSET="esp32c6" and it goes to this case:
![image](https://github.com/espressif/esp-hosted/assets/49090258/08f3b6af-4499-492d-90d8-83fc045e4770)

It expects '-' between "32" and "c"

**Comment by mantriyogesh** [comment]
Both cases are covered, right?
https://github.com/espressif/esp-hosted/blob/master/esp_hosted_fg/host/linux/host_control/rpi_init.sh#L211-L218

Basically. `ESP32C6` or `ESP32-C6` both should be able to be used.

**Comment by NikolayTsvetkovv** [comment]
It seems I used old version. Yes you are right, the problem is fixed in this file: https://github.com/espressif/esp-hosted/blob/master/esp_hosted_fg/host/linux/host_control/rpi_init.sh#L211-L218
