### ISSUE TITLE
esp32c3 wifi transmit power

### ISSUE THREAD

**Issue by C-sjia** [espressif/esp-hosted#329]
What is the default value of wifi if the transmit power is not configured？

**Comment by mantriyogesh** [comment]
May I ask which variant you are interested in?
FG or NG?

**Comment by C-sjia** [comment]
NG mode

**Comment by mantriyogesh** [comment]
@kapilkedawat ++

**Comment by kapilkedawat** [comment]
Hi @C-sjia, incase trasnmit power is not configured, device will use:
`min[max tx power of chip, max tx power allowed by regulatory]`.

**Comment by C-sjia** [comment]
okey. thank you.

**Comment by kapilkedawat** [comment]
Hi @C-sjia, Please close this issue if this answers your query.
