### ISSUE TITLE
Dataready   and Handshake io  dirction

### ISSUE THREAD

**Issue by lipengvita** [espressif/esp-hosted#351]
In use esp-host-ng funciton ，Could you explain the direciton of dataread iterrupte and handshake direciton

**Comment by lipengvita** [comment]
Could you explain the direciton of dataread iterrupt and handshake iterrupt

**Comment by mantriyogesh** [comment]
In both FG or NG, SPI bus is same.
Please refer
[SPI_design_note.pdf](https://github.com/espressif/esp-hosted/files/14519816/SPI_design_note.pdf)
for pin understanding
