### ISSUE TITLE
Are both the reset pin and the enable pin necessary?

### ISSUE THREAD

**Issue by lipengvita** [espressif/esp-hosted#352]
Acorrding the esp-host-ng main. c "MODULE_PARM_DESC(resetpin, "Host's GPIO pin number which is connected to ESP32's EN to reset ESP32 device"); " ,  Just notify the resetpin  to reset esp32 ，not use the enable gpio。 Dose it mean Just need connect EN or Reset on pin to the cpu

**Comment by mantriyogesh** [comment]
Some ESP chipsets have 'RST' pin, while others have 'EN'.
Yes the idea is whichever is available on your ESP chipset , you can connect it to your MCU/MPU GPIO.

MCU/MPU is controller of this pin output. You may need to configure this pin.
In Linux, say using Device tree conf.
In MCU, the configuration tool supported or through the code.
