### ISSUE TITLE
rpi_init.sh spi Build failure

### ISSUE THREAD

**Issue by LSPgh** [espressif/esp-hosted#36]
Hi,

I am seeing the following when attempting to compile the esp-hosted driver.
![Screenshot from 2021-07-02 11-16-47-modifed](https://user-images.githubusercontent.com/77275854/124260308-7189dd00-db27-11eb-8362-1972528c2218.png)

Any ideas on sorting this issue?

**Comment by ajita02** [comment]
Hi @LewisPurvis89 , please use latest code base of ESP-Hosted master. It has solution for latest kernel compilation error.

**Comment by LewisPurvis89** [comment]
That fixed the issue, i was using release/v0.3. Thanks.

**Comment by ajita02** [comment]
Hi @LSPgh , Good to hear it solved your problem. Can you help to close this issue?
Thanks,
Ajita
