### ISSUE TITLE
default transmission power of WiFi and Bluetooth for the esp32-c3 chip

### ISSUE THREAD

**Issue by linchanghe123** [espressif/esp-hosted#368]
Hi, mantriyogesh

What are the default transmission power of WiFi and Bluetooth for the esp32-c3 chip in esp_hosted_ng and esp_hosted_fg modes, respectively?

**Comment by mantriyogesh** [comment]
Hello @linchanghe123 ,

## Wi-Fi
If not configured, default power for Wi-Fi for any ESP chipset would be:
`min[max tx power of chip, max tx power allowed by regulatory]`

NG: https://github.com/espressif/esp-hosted/issues/329
FG: https://github.com/espressif/esp-hosted/blob/master/esp_hosted_fg/host/linux/host_control/c_support/test.c#L95-L98

Let me confirm for Bluetooth

**Comment by linchanghe123** [comment]
Thank you. Looking forward to your further reply.

> Hello @linchanghe123 ,
> 
> ## Wi-Fi
> If not configured, default power for Wi-Fi for any ESP chipset would be: `min[max tx power of chip, max tx power allowed by regulatory]`
> 
> NG: #329 FG: https://github.com/espressif/esp-hosted/blob/master/esp_hosted_fg/host/linux/host_control/c_support/test.c#L95-L98
> 
> Let me confirm for Bluetooth

**Comment by linchanghe123** [comment]
Bluetooth power is temporarily not being monitored, close issue.

**Comment by mantriyogesh** [comment]
The default bluetooth transmit power for all ESP chipset is +9dBm.
