### ISSUE TITLE
Does esp32c3 support secure boot?

### ISSUE THREAD

**Issue by xmlhp** [espressif/esp-hosted#372]
Does esp32c3 support secure boot?
Our product needs to support secure boot?
How to do safe boot?
If supported, how to package the hosted-ng firmware?

**Comment by mantriyogesh** [comment]
Hello @xmlhp ,

Secure boot is supported on ESP chipsets.
It is feature directly usable from ESP-IDF (and hence ESP-Hosted also supports it)

Please check [documentation](https://docs.espressif.com/projects/esp-idf/en/v5.2.1/esp32c3/security/index.html) and [blog](https://blog.espressif.com/understanding-esp32s-security-features-14483e465724)
