### ISSUE TITLE
Does esp32C3 support two chips connect witch one spi master

### ISSUE THREAD

**Issue by lipengvita** [espressif/esp-hosted#377]

**Comment by lipengvita** [comment]
I means  host as spi master and connect two esp32c3 which two are slave ，the comunction is controled by NSS

**Comment by mantriyogesh** [comment]
Hello @lipengvita ,

ESP-Hosted works with SPI as slave.
Is the host controlling the slave with individual CS pins?
If so, it should work fine.

I am trying to understand the use case, as it might be more of [ESP-IDF](https://github.com/espressif/esp-idf) use case and may or may not need ESP-Hosted.

**Comment by lipengvita** [comment]
thks

**Comment by mantriyogesh** [comment]
Can we close this issue, if you have no further questions?

**Comment by lipengvita** [comment]
thks
