### ISSUE TITLE
build esp-hosted-ng error

### ISSUE THREAD

**Issue by XZ-Niupitang** [espressif/esp-hosted#391]
![image](https://github.com/espressif/esp-hosted/assets/103943684/8f24eff8-9e54-42fb-9121-345c49bb05a0)
I have installed the esp-idf V5.2.1 compilation environment locally and followed the installation steps step by step. The lib copy of setup.sh has also been completed, but this error is still reported. What is the reason?

**Comment by mantriyogesh** [comment]
Have you followed https://github.com/espressif/esp-hosted/blob/master/esp_hosted_ng/esp/esp_driver/README.md#update-build-firmware-for-esp-hosted-ng-solution  for firmware flashing on master branch latest commit?

If so, it should work. Can you please show the output log if it fails?

**Comment by XZ-Niupitang** [comment]
The local esp-idf compilation environment is installed by itself and get_idf (export.sh) is declared in /etc/profile. There is no problem compiling the routines in the example. I did not use git clone to download the source code directly, but just After downloading the code-zip of esp-hosted to local decompression and then pressing setup to execute it, the wifi library reported at the beginning is undefined and does not appear after replacing the files in esp-idf-v5.2.1/components/esp_wifi/lib/. Instead, this new question
![image](https://github.com/espressif/esp-hosted/assets/103943684/9240ca12-b3ae-4fa0-80b6-d1f7cc1092ac)
Every time I compile, I get stuck at the position in the picture.

**Comment by XZ-Niupitang** [comment]
> 您是否遵循[了 https://github.com/espressif/esp-hosted/blob/master/esp_hosted_ng/esp/esp_driver/README.md#update-build-firmware-for-esp-hosted-ng-solution](https://github.com/espressif/esp-hosted/blob/master/esp_hosted_ng/esp/esp_driver/README.md#update-build-firmware-for-esp-hosted-ng-solution) 在主分支最新提交时刷新固件？
> 
> 如果是这样，它应该有效。如果失败，您能否显示输出日志？
The local esp-idf compilation environment is installed by itself and get_idf (export.sh) is declared in /etc/profile. There is no problem compiling the routines in the example. I did not use git clone to download the source code directly, but just After downloading the code-zip of esp-hosted to local decompression and then pressing setup to execute it, the wifi library reported at the beginning is undefined and does not appear after replacing the files in esp-idf-v5.2.1/components/esp_wifi/lib/. Instead, this new question
![image](https://github.com/espressif/esp-hosted/assets/103943684/9240ca12-b3ae-4fa0-80b6-d1f7cc1092ac)
Every time I compile, I get stuck at the position in the picture.

**Comment by mantriyogesh** [comment]
Currently, for NG, you cannot use your own IDF. the IDF would be used from the commit pushed as part of esp_hosted_ng/esp/esp_driver/esp-idf

But you do not need to do it manually, it is already automated with instructions.
If you do `get_idf()` and it is different from the one in  `esp_hosted_ng/esp/esp_driver/esp-idf`, it is expected to fail.

So please run one by instruction carefully from, https://github.com/espressif/esp-hosted/issues/391#issuecomment-2126696076
Please attach **textual** log of **all** steps.

**Comment by XZ-Niupitang** [comment]
> Currently, for NG, you cannot use your own IDF. the IDF would be used from the commit pushed as part of esp_hosted_ng/esp/esp_driver/esp-idf
> 
> But you do not need to do it manually, it is already automated with instructions. If you do `get_idf()` and it is different from the one in `esp_hosted_ng/esp/esp_driver/esp-idf`, it is expected to fail.
> 
> So please run one by instruction carefully from, [#391 (comment)](https://github.com/espressif/esp-hosted/issues/391#issuecomment-2126696076) Please attach **textual** log of **all** steps.

Successfully compiled and downloaded to the board, thank you for your support
