### ISSUE TITLE
WiFi transmission rate

### ISSUE THREAD

**Issue by linchanghe123** [espressif/esp-hosted#392]
Hi mantriyogesh,

Using ng mode, When connecting to WiFi with good WiFi signals, the tested UDP transmission rate is only about 100KB/S. The TCP transmission rate is approximately 300KB/S.

 Is there any way to increase the transmission rate? Attempted to increase the SPI bus frequency from 10M to 40M, but it seems to have little effect.

TCP：
![image](https://github.com/espressif/esp-hosted/assets/15261661/df446fd7-51a8-4470-8c82-0ea865e857bc)

UDP:
![image](https://github.com/espressif/esp-hosted/assets/15261661/afcdb4d7-0c39-47c4-a0b6-bbbf29097c15)

**Comment by mantriyogesh** [comment]
This is excessively low.

Worth to separate Wi-Fi and transport speeds.

To isolate and test your transport, test the [raw transport throughput](https://github.com/espressif/esp-hosted/blob/master/esp_hosted_ng/docs/Raw_TP_Testing.md) in tx and rx direction.

**Comment by mantriyogesh** [comment]
I see the issue closed, but not sure if it was working for you.

Have you managed to check your raw transport throughput?
Do let us know if anything required/ unclear.
