### ISSUE TITLE
esp32c6 mini GPIO question

### ISSUE THREAD

**Issue by XZ-Niupitang** [espressif/esp-hosted#398]
Can the SPI pins of the driver in esp-host-fg be changed freely?
<img width="348" alt="image" src="https://github.com/espressif/esp-hosted/assets/103943684/ae358574-0c30-4461-962b-376d8ad81e52">
<img width="385" alt="image" src="https://github.com/espressif/esp-hosted/assets/103943684/ba617e04-4c21-4bff-a86f-42cd6363452f">

**Comment by mantriyogesh** [comment]
For ESP32-C6, yes, just try to avoid the bootstrapping pins to be used

**Comment by mantriyogesh** [comment]
Hello @XZ-Niupitang ,

Unless they are already in use (say by sdio or any other function), any on bootstrapping gpios could be used.

Check https://docs.espressif.com/projects/esp-idf/en/v5.2.1/esp32c6/api-reference/peripherals/spi_slave.html#gpio-matrix-and-io-mux


When you use any other gpios than that of IO_MUX, they would route through GPIO matrix.
Obviously there would be minor delays in that, but overall ESP32-C6 should withstand. The max freq we tested for ESP32-C6 as spi slave is 26MHz.

However, the ESP32-C6 is used on PCB. for jumper cables, lower frequencies are suggested to be used.

**Comment by XZ-Niupitang** [comment]
> Hello @XZ-Niupitang ,
> 
> Unless they are already in use (say by sdio or any other function), any on bootstrapping gpios could be used.
> 
> Check https://docs.espressif.com/projects/esp-idf/en/v5.2.1/esp32c6/api-reference/peripherals/spi_slave.html#gpio-matrix-and-io-mux
> 
> When you use any other gpios than that of IO_MUX, they would route through GPIO matrix. Obviously there would be minor delays in that, but overall ESP32-C6 should withstand. The max freq we tested for ESP32-C6 as spi slave is 26MHz.
> 
> However, the ESP32-C6 is used on PCB. for jumper cables, lower frequencies are suggested to be used.

After trying to modify the interface, I found that I could no longer communicate with the Raspberry Pi. The driver of the Raspberry Pi was not modified. The c6 program was modified as follows. The startup log is as follows:
![image](https://github.com/espressif/esp-hosted/assets/103943684/b678aeb3-7ab3-40ea-87b8-d70ee415cacc)
<img width="384" alt="image" src="https://github.com/espressif/esp-hosted/assets/103943684/dabf5790-8dc4-4623-adbd-f4a829a38020">
<img width="702" alt="image" src="https://github.com/espressif/esp-hosted/assets/103943684/e703e9b3-9f67-440b-a7df-becebfca223d">
The actual hardware wiring is only changed in the C6 test board, the Raspberry Pi is unchanged.

**Comment by mantriyogesh** [comment]
Setup photo please?

`git diff` at both places?

**Comment by XZ-Niupitang** [comment]
> Setup photo please?
> 
> `git diff` at both places?

The only changes made are:
<img width="834" alt="image" src="https://github.com/espressif/esp-hosted/assets/103943684/539d9ba0-8b7f-411c-af61-0d10e7eb11a4">

**Comment by XZ-Niupitang** [comment]
It's ok, it looks like the modification was successful, sometimes life is fucked up

**Comment by FlSenicar** [comment]
Hello @XZ-Niupitang 
Can you tell me what you did to fix this issue? I am currently experiencing the same issue after remapping the SPI to other Gpios. 
The data seems to be shifted by one bit. Whenever I move the SPI back to the original IOs everything works fine.
Thank you very much!
