### ISSUE TITLE
SPI communication abnormality after driver transplantation (ESP_HOST_FG)

### ISSUE THREAD

**Issue by XZ-Niupitang** [espressif/esp-hosted#402]
The main control chip is TI's TDA4VM, and the onboard WIFI chip is ESP32C6. It can communicate with the onboard wifi module normally through USB. After porting the esp_host_fg driver to TDA4VM, it is found that TDA4VM can send SPI signal communication normally, but ESP32C6 does not respond normally, MISO has no level change, and the GPIO interrupts of HandShack and DateRead are normal.

![image](https://github.com/espressif/esp-hosted/assets/103943684/330d23da-be71-4d08-a3eb-0394e285ad16)

After checking the PCB, I found that there is no broken wire, but there is currently no normal communication. What troubleshooting ideas do you have?

WIFI LOGO :
![image](https://github.com/espressif/esp-hosted/assets/103943684/2bc93136-1020-4ebc-999d-a0e13af2aa14)

The modified (esp_spi_transaction ) function code is as follows 
![image](https://github.com/espressif/esp-hosted/assets/103943684/809bbb34-bcc8-4670-94ce-0de3ab772d2a)

The system log of the mounted driver is as follows
![image](https://github.com/espressif/esp-hosted/assets/103943684/849c170e-3ab1-404a-92b9-6e8b869177c9)

**Comment by mantriyogesh** [comment]
Hello @XZ-Niupitang ,

Will check this in detail and come up with initial  response tomorrow

**Comment by mantriyogesh** [comment]
Can you please state the performance you receive in raw throughput in rx and tx direction?
I think, before jumping to higher levels and wifi, this is important metric to understand and have confidence in transport layer.

Higher layers have n number of factors for the performance gain/loose. however, raw throughput would depict how the spi performs without other layer intervention

**Comment by XZ-Niupitang** [comment]
> Can you please state the performance you receive in raw throughput in rx and tx direction? I think, before jumping to higher levels and wifi, this is important metric to understand and have confidence in transport layer.
> 
> Higher layers have n number of factors for the performance gain/loose. however, raw throughput would depict how the spi performs without other layer intervention

Thanks for your reply. My question is how to test the communication performance of the SPI interface of the TDA4VM chip? This should be determined by hardware.

**Comment by mantriyogesh** [comment]
You are absolutely right. It depends on hardware & underlying spi driver for you SoC. You can first test with spidev to understand the performance.

Then you can run  [raw throughout test](https://github.com/espressif/esp-hosted/blob/master/esp_hosted_fg/docs/Linux_based_host/Raw_TP_Testing.md) in tx and rx to assess the transport speed. If any issues here, higher layers will suffer, including ESP-Hosted driver.

Make sure checksum is enabled using IDF.py menuconfig -> 'example configuration ', which would make sure the messages integrity is tested.

Also please check [porting guide](https://github.com/espressif/esp-hosted/blob/master/esp_hosted_fg/docs/Linux_based_host/porting_guide.md)

**Comment by XZ-Niupitang** [comment]
> You are absolutely right. It depends on hardware & underlying spi driver for you SoC. You can first test with spidev to understand the performance.
> 
> Then you can run [raw throughout test](https://github.com/espressif/esp-hosted/blob/master/esp_hosted_fg/docs/Linux_based_host/Raw_TP_Testing.md) in tx and rx to assess the transport speed. If any issues here, higher layers will suffer, including ESP-Hosted driver.
> 
> Make sure checksum is enabled using IDF.py menuconfig -> 'example configuration ', which would make sure the messages integrity is tested.
> 
> Also please check [porting guide](https://github.com/espressif/esp-hosted/blob/master/esp_hosted_fg/docs/Linux_based_host/porting_guide.md)

Thank you for your reply. After trying to increase the communication rate to 20Mhz, the file transfer speed reached 420kb/s. Is there room for further optimization?
I will post the throughput test results later.
![image](https://github.com/espressif/esp-hosted/assets/103943684/26d0e8dd-7856-4e39-9ba4-e7365bd326fc)

**Comment by mantriyogesh** [comment]
Considering 20Mhz , 420 kBps = 3.3Mbps is extremely slow.

Anyway, my input would be the same, to https://github.com/espressif/esp-hosted/issues/402#issuecomment-2167440971

The test you perform have n number of factors in consideration. Please test raw throughout to assess your transport instead of jumping to iperf or file download test, asking with checksum enabled.

**Comment by XZ-Niupitang** [comment]
> Considering 20Mhz , 420 kBps = 3.3Mbps is extremely slow.
> 
> Anyway, my input would be the same, to [#402 (comment)](https://github.com/espressif/esp-hosted/issues/402#issuecomment-2167440971)
> 
> The test you perform have n number of factors in consideration. Please test raw throughout to assess your transport instead of jumping to iperf or file download test, asking with checksum enabled.

I understand. I will continue to look for problems later. If there are any findings or questions, I will synchronize them in time. Thank you.
