### ISSUE TITLE
ESP-Hosted-FG ，linux-hosted,sdio write buffer calcuate

### ISSUE THREAD

**Issue by MrHaiCoder** [espressif/esp-hosted#403]
Can you explain in detail the principle of calculating the buffer for this function---is_sdio_write_buffer_available（）

**Comment by mantriyogesh** [comment]
Please co-relate with:
https://docs.espressif.com/projects/esp-idf/en/v4.2/esp32/api-reference/peripherals/esp_slave_protocol.html#receiving-fifo
