### ISSUE TITLE
Where can I find enumeration of the reasons for the disconnection?

### ISSUE THREAD

**Issue by ShengjieCh** [espressif/esp-hosted#427]
Where can I find enumeration of the reasons for the disconnection?

https://github.com/espressif/esp-hosted/blob/master/esp_hosted_fg/docs/common/ctrl_apis.md#415-struct-event_station_disconn_t
![GTScreenshot_20240709_144237](https://github.com/espressif/esp-hosted/assets/56919534/ba3ebbea-75f7-4259-95d9-d4437ecf9a84)

**Comment by mantriyogesh** [comment]
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/network/esp_wifi.html#_CPPv417wifi_err_reason_t

**Comment by mantriyogesh** [comment]
https://github.com/espressif/esp-idf/blob/3b8741b172dc951e18509698dee938304bcf1523/components/esp_wifi/include/esp_wifi_types.h#L78-L140

**Comment by ShengjieCh** [comment]
thanks~

**Comment by ShengjieCh** [comment]
Sorry, I didn't find the enumeration of 0. What is the definition of this?
![image](https://github.com/espressif/esp-hosted/assets/56919534/32383fbf-a89b-4b27-9555-2c6cc4081b81)

**Comment by mantriyogesh** [comment]
0 shouldn't have come as such.

**Comment by mantriyogesh** [comment]
The reason for disconnection is not populated currently for sta disconnected from ESP softap.
only mac address is sent to identify which station got disconnected.

We would need to add the reason in this event.
![Screenshot 2024-07-09 at 7 26 58 PM](https://github.com/espressif/esp-hosted/assets/67477199/dd4b299e-f537-4f7d-8cf2-a14b5552ff06)

**Comment by ShengjieCh** [comment]
Please let me know approximately when this feature will be supported.
