### ISSUE TITLE
When I use test_enable_wifi, enable feature times out. host-fg

### ISSUE THREAD

**Issue by ShengjieCh** [espressif/esp-hosted#434]
![image](https://github.com/user-attachments/assets/8f6ce495-c1c2-4a9e-a6d1-334470948a34)
How should I use this function? Are there any preconditions required?
I used like this, will there be any problems?
![image](https://github.com/user-attachments/assets/77ae6f16-3407-4b2c-9361-e006d486d316)

**Comment by mantriyogesh** [comment]
Please add in https://github.com/espressif/esp-hosted/issues/405 , as it is already open for same issue by you.
