### ISSUE TITLE
FG mode WiFi status reporting issue

### ISSUE THREAD

**Issue by linchanghe123** [espressif/esp-hosted#435]
Hi mantriyogesh,

Feedback on an issue with the NG mode: In the code on the ESP32 side, the function req_connect_ap_handler reports WiFi connection status, SSID errors, and password errors, which are overwritten, causing the host to be unable to obtain detailed error status.

![image](https://github.com/user-attachments/assets/ad351362-a9d5-441d-bb4c-a623d88c88ff)

**Comment by mantriyogesh** [comment]
Yes, originally we only sent success or failure , the log at ESP shows the problem encountered.

This needs a fix in all apis to send back all the real failure integer.

At 
https://github.com/espressif/esp-hosted/blob/a00a99ba35a805a5166bac8aea6fd4741db6a4e5/esp_hosted_fg/esp/esp_driver/network_adapter/main/slave_control.c#L434

We can initialise resp as:
```
resp_payload->resp =  FAILURE;
```
and comment  the line, 

https://github.com/espressif/esp-hosted/blob/a00a99ba35a805a5166bac8aea6fd4741db6a4e5/esp_hosted_fg/esp/esp_driver/network_adapter/main/slave_control.c#L603

This is still workaround, proper fix to fix all the apis to return the failure. We will fix this.
