### ISSUE TITLE
NG mode, WiFi connected, signal poll get rssi not refresh

### ISSUE THREAD

**Issue by lwj850533527** [espressif/esp-hosted#441]
Hi mantriyogesh,

Feedback on an issue with the NG mode.
After connected the AP, use "wpa_cli signal_poll" get rssi, but it doesn't seem to refresh
When use  "wpa_cli scan",  signal level refresh, but it doesn't refresh to signal_poll

![image](https://github.com/user-attachments/assets/bd6c40e7-8f55-4f49-8428-872b2396c297)

**Comment by mantriyogesh** [comment]
@kapilkedawat , PTAL.

**Comment by lwj850533527** [comment]
Hi mantriyogesh
Hi kapilkedawat 
@mantriyogesh , @kapilkedawat 
Due to the inability to report signal rssi,  I tried using the scan interface to perform regular scans.
To prevent signal disconnection, I need to limit the scanning frequency band to be consistent with the connected AP.

"wpa_cli SCAN freq=2457", The instruction sent to wpa_supplicant has taken effect, but the slave still performs scanning of all frequency bands
[dmesg.txt](https://github.com/user-attachments/files/16536800/dmesg.txt)
![image](https://github.com/user-attachments/assets/dddbf50f-3345-4ea5-9144-b71a2b49bfff)

**Comment by kapilkedawat** [comment]
@lwj850533527 fixed in latest master
