### ISSUE TITLE
NG mode, WiFi connected Multiple AP same ssid, connection use for a long time

### ISSUE THREAD

**Issue by lwj850533527** [espressif/esp-hosted#442]
Hi mantriyogesh,

Feedback on an issue with the NG mode.The scene is connecting multiple APs same ssid. Sometimes the connection use for a long time.
As shown in the figure，“06:f9:f8:1f:cd:fd”,“06:f9:f8:14:69:c7”,"06:f9:f8:14:66:4c"，these three are APs with the same SSID and password.
14:35:12, it initiated an AP connection
14:36:46 it connect success
The connection cost 1.5 minutes

From packet capture data, ESP32 sends authentication to an incorrect MAC address.For example: 14:35:14, kernel log it should sents authentication to “06:f9:f8:1f:cd:fd”, but cat packet it sents to “06:f9:f8:14:69:c7”
From esp32c3 log, 14:35:14, it seems received an authentication response, but the processing result is abnormal

it is kernel log
![image](https://github.com/user-attachments/assets/373e514c-b764-47dd-b946-76a78c95c61f)

it is esp32c3 log
![image](https://github.com/user-attachments/assets/353b4a89-e1ea-453f-aa6f-af1a7d33edc7)
![image](https://github.com/user-attachments/assets/5abac4d3-bd41-4e8c-803b-8dc276d921be)
![image](https://github.com/user-attachments/assets/20624462-9243-4911-900b-a8ca4e98e577)
![image](https://github.com/user-attachments/assets/b2a2bf29-6fb3-4788-b3e4-e66587f83129)

it is omnipeek air interface packet capture data
![image](https://github.com/user-attachments/assets/6a50ba65-e263-47d7-8559-fde60960724c)

**Comment by mantriyogesh** [comment]
@kapilkedawat , PTAL.

**Comment by lwj850533527** [comment]
@mantriyogesh 
Is there any progress on this issue

**Comment by kapilkedawat** [comment]
Hi @lwj850533527, could you please share above dmesg, sniffer capture and firmware logs ?

**Comment by lwj850533527** [comment]
@kapilkedawat 
dmesg not saved， only screenshots available
![image](https://github.com/user-attachments/assets/72d9d64b-9e64-4af1-b9d9-c8de57be36cf)
[sniffer capture.zip](https://github.com/user-attachments/files/16520732/sniffer.capture.zip)
[firmware logs.txt](https://github.com/user-attachments/files/16520734/firmware.logs.txt)

**Comment by lwj850533527** [comment]
@kapilkedawat
I found some related settings. Is the MAC address incorrect due to lack of settings
bool bssid_set;
whether set MAC address of target AP or not. Generally, station_config.bssid_set needs to be 0; and it needs to be 1 only when users need to check the MAC address of the AP

![image](https://github.com/user-attachments/assets/c154584e-db62-42d9-9a2b-745b67d57e5f)
![image](https://github.com/user-attachments/assets/e2b76737-ab41-490b-b044-fa86357453ea)

**Comment by kapilkedawat** [comment]
@lwj850533527 please recheck in latest mater.
