### ISSUE TITLE
NG mode, WiFi connected hide ssid failed

### ISSUE THREAD

**Issue by lwj850533527** [espressif/esp-hosted#443]
Hi mantriyogesh,

Feedback on an issue with the NG mode.
I want connect to hide ssid AP.
Set the scan_ssid = 1, wpa_supplicant can scan the ap, but can't connected.
Does it require any other operations

wpa_cli scan log:
![image](https://github.com/user-attachments/assets/a22a2331-00f8-43b8-beaa-145d90c39f33)

esp32 log
![image](https://github.com/user-attachments/assets/14737c9e-bc26-4ff5-97f1-200869e5c5f0)

kernel log
![image](https://github.com/user-attachments/assets/146800a0-88e0-447c-b71f-e265d4317157)

wpa_supplicant.conf
![image](https://github.com/user-attachments/assets/32f16525-6b99-4f8f-98dd-2b5af8f6f033)

**Comment by mantriyogesh** [comment]
@kapilkedawat, PTAL

**Comment by lwj850533527** [comment]
Hi mantriyogesh,
I found some related settings

![image](https://github.com/user-attachments/assets/d92da348-7500-40f4-8888-6eddcafacb4c)
![image](https://github.com/user-attachments/assets/642aa63c-4e9c-44f8-92cc-897d02d8ffd9)

**Comment by mantriyogesh** [comment]
Yes, let we verify/fix this.
@kapilkedawat ++

**Comment by lwj850533527** [comment]
Hi mantriyogesh,
Hi kapilkedawat,
I try to set up show_hidden to true, it seems to have already searched for this AP.
But in the end, the esp_wifi_connect interface returned a failure.
Do I need to make any other settings
![image](https://github.com/user-attachments/assets/3e8fc105-046e-41c0-b8f2-9654af02e9a1)
![image](https://github.com/user-attachments/assets/c62c0692-3ec7-4911-a48b-3bc690256f32)
![image](https://github.com/user-attachments/assets/271f60ac-301d-4e3e-b538-2fdd0da96ee3)

**Comment by kapilkedawat** [comment]
Hi @lwj850533527 , please wait we will be fixing this.

**Comment by kapilkedawat** [comment]
Hi @lwj850533527 fixed in https://github.com/espressif/esp-hosted/commit/8445046094e7a09afe6dd4d3494801b472a85f73
