### ISSUE TITLE
SoftAP mode support availability

### ISSUE THREAD

**Issue by QuiGonRazor** [espressif/esp-hosted#449]
Hello,
quick issue to ask you if SoftAP mode is supported with hosted_NG driver

As  per your README it is a future feature not yet implemented but I've checked into your sources and it seems there's a possibility to enable also AP_mode

Can you confirm it is not yet supported?

**Comment by mantriyogesh** [comment]
It is under testing now, we would release it asap.
@kapilkedawat PTAL.

**Comment by QuiGonRazor** [comment]
Thank you
I'm closing the issue as you have answered to my question even if the feature is not available yet
