### ISSUE TITLE
NG mode, disconnect event cannot report

### ISSUE THREAD

**Issue by lwj850533527** [espressif/esp-hosted#474]
Hi @kapilkedawat.

I use the latest code for testing. But the disconnect event cannot report
It can only report "WPA_EVENT_REGDOM_CHANGE" event. 
I deleted the change in this commit https://github.com/espressif/esp-hosted/commit/20c88e58ca59d1aaf0b807b77c907e2567b9fea6
It can report disconnect event normally

![image](https://github.com/user-attachments/assets/61187d43-52dc-4510-a3c5-55377611f56b)

**Comment by kapilkedawat** [comment]
Hi @lwj850533527, could you please share supplicant logs? https://github.com/espressif/esp-hosted/commit/20c88e58ca59d1aaf0b807b77c907e2567b9fea6 makes sure that supplicant doesn't get dummy deauth frame when disconnect was issued from userspace(this messes up supplicant's state machine sometimes). Also how are you disconnecting the station from AP?

**Comment by lwj850533527** [comment]
> Also how are you disconnecting the station from AP?

I turned off the power of the router

**Comment by kapilkedawat** [comment]
Please share supplicant logs and dmesg.

**Comment by lwj850533527** [comment]
I tried to reproduce it, but it doesn't seem to certainly happen

**Comment by kapilkedawat** [comment]
Please do share the logs when you are able to reproduce it. As I mentioned above, the patch above fixes a specific issue and decrease our total connection time in that case.

**Comment by kapilkedawat** [comment]
@lwj850533527 can we close this if this issue no longer comes in your setup?

**Comment by lwj850533527** [comment]
Hi @kapilkedawat.
OK.
We can reopen this issue if the next time same problem happen
