### ISSUE TITLE
Command[1] timed out

### ISSUE THREAD

**Issue by ZlTpiger** [espressif/esp-hosted#480]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Provided a clear description of your suggestion.
- [X] Included any relevant context or examples.

### Issue or Suggestion Description

I use1.0.2 release version,and use Raspberry Pi 4 Model B and esp32,why can not add_network_iface
![image](https://github.com/user-attachments/assets/28fc7d85-2efd-4ef1-870d-3f7a8bc64924)

**Comment by ZlTpiger** [comment]
Both host and esp32 driver are use 1.0.2 release version

**Comment by mantriyogesh** [comment]
The spi is not showing correct transaction. 
What is frequency you use right now, what is the spi mode both sides?

**Comment by mantriyogesh** [comment]
Also, I am closing this as this counted as feature request. Please open up a bug report, newly.
