### ISSUE TITLE
Pin on ESP32-C3

### ISSUE THREAD

**Issue by freetoair** [espressif/esp-hosted#499]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Provided a clear description of your suggestion.
- [X] Included any relevant context or examples.

### Issue or Suggestion Description

Hi, 
 I have one doubt that I would like to clarify. Namely, I have successfully compiled the esp-host driver for Rockchip RV 1103 SoC and esp32-C3 firmware, but when I try to enter esp32_spi.ko with insmod esp32_spi.ko the process gets stuck and does not respond any further. Since everything went fine with the software I thought it was a connection between Luckfox-pico and the ESP32-C3 Super mini board. The pins that connect according to the Git hub instructions are different from those on the Super-mini board. Which pins should be considered valid? Can I find from the ESP-IDF project how the pin-mux is done in the project for the SPI version of the connection?

**Comment by mantriyogesh** [comment]
It doesn't like this is feature suggestion. So we left out to close this. Please open as bug and add in the logs as bug description says.
