### ISSUE TITLE
How to interpret src revisions on host and network-adapter

### ISSUE THREAD

**Issue by vardan** [espressif/esp-hosted#504]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Provided a clear description of your suggestion.
- [X] Included any relevant context or examples.

### Issue or Suggestion Description

Hi,

Can you guide me hot to interpret srcrevision in the kernel module description? It is clearly not a commit id it has been built on

```
filename:       /home2/vsaakian/work/build/./tmp-glibc/sysroots-components/stm32mp1_pixie/esp-hosted-ng/lib/modules/5.10.116/extra/esp32_spi.ko
softdep:        pre: spi_stm32
version:        NG-1.0.3.0.0
description:    Wifi driver for ESP-Hosted solution
author:         Kapil Gupta <kapil.gupta@espressif.com>
author:         Yogesh Mantri <yogesh.mantri@espressif.com>
author:         Mangesh Malusare <mangesh.malusare@espressif.com>
author:         Amey Inamdar <amey.inamdar@espressif.com>
license:        GPL
**srcversion:     C54ABD5BB7962F49CE68DC4**
depends:        cfg80211,bluetooth
name:           esp32_spi
vermagic:       5.10.116 SMP preempt mod_unload modversions ARMv7 p2v8 
parm:           resetpin:Host's GPIO pin number which is connected to ESP32's EN to reset ESP32 device (int)
parm:           clockspeed:Hosts clock speed in MHz (uint)
parm:           raw_tp_mode:Mode choosed to test raw throughput (uint)
```

Same for network-adapter output - where can I see commit id it has been built on?

I am trying to bump both host and network-adapter to the latest version and there's clearly a mismatch of versions as I keep getting printouts of drop packets like following:
```
[ 1517.062899] esp32_spi: spi_dev_init: ESP32 peripheral is registered to SPI bus [5],chip select [0], SPI Clock [10]
[ 1518.596709] esp32_spi: process_rx_buf: offset_rcv[0] != exp[12], drop
```
I was previously on version 61c9415c1eb619787cc151dadc708780a172a413

**Comment by mantriyogesh** [comment]
Please close the feature request and open bug request, with full text logs both sides. also, include the git commits used both sides.
