### ISSUE TITLE
Sometimes events cannot be handled in a timely manner

### ISSUE THREAD

**Issue by vrolife** [espressif/esp-hosted#507]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Provided a clear description of your suggestion.
- [X] Included any relevant context or examples.

### Issue or Suggestion Description

FIx patch

```diff
@@ -945,14 +968,12 @@ static void esp_events_work(struct work_struct *work)
 {
        struct sk_buff *skb = NULL;
 
-       skb = skb_dequeue(&adapter.events_skb_q);
-       if (!skb)
-               return;
-
-       if (skb->data) {
-               process_internal_event(&adapter, skb);
+       while ((skb = skb_dequeue(&adapter.events_skb_q)) != NULL) {
+               if (skb->data) {
+                       process_internal_event(&adapter, skb);
+               }
+               dev_kfree_skb_any(skb);
        }
-       dev_kfree_skb_any(skb);
 }
```

**Comment by mantriyogesh** [comment]
Can you please suggest what host you use, slave you use, git commit and the issue you faced?

It works be easy to then relate if this is the main cause or after effect that you are trying to solve.

**Comment by vrolife** [comment]
My host is f1c100s+Linux 6.6, and the board is esp32s2+esp-hosted-ng. I use the esp32s2 to listen for GPIO interrupts to implement key press events, which are sent to Linux via SPI + interface_buffer_handle_t + ESP_INTERNAL_IF. When the key is pressed rapidly multiple times, the key press events accumulate in adapter.events_skb_q without being processed, because esp_events_work processes only one event at a time.
