### ISSUE TITLE
FG mode, ctrl_req_sem semaphore no post

### ISSUE THREAD

**Issue by lwj850533527** [espressif/esp-hosted#527]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [X] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [X] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

ctrl_req_sem semaphore get and post are matching
![image](https://github.com/user-attachments/assets/c4ce00a1-8d1e-4385-8972-56ed37250dbd)

### Actual behavior (suspected bug)

When the SSID length I set is too long, it can return normally this time
![image](https://github.com/user-attachments/assets/85e175ce-b50f-4a5f-8272-f8ed80be1882)

But the next time, all command cannot get semaphore
![image](https://github.com/user-attachments/assets/56b95372-9cab-462e-b3c3-64c0f68e9d1b)

### Error logs or terminal output

```shell
resp NULL                                                                       
[ctrl_app_send_req]1250                                                         
Failed to send control req 123                                                  
resp NULL                                                                       
null version:-0.0.0.0.0                                                         
[ctrl_app_send_req]1250                                                         
Failed to send control req 101                                                  
Failed to get wifi mac                                                          
esp32 mac init err:0xffffffff
```

### Steps to reproduce the behavior

SSID length set too long

### Project release version

0.0.6.0.0

### System architecture

ARM 64-bit (Apple M1/M2, Raspberry Pi 4/5)

### Operating system

Linux

### Operating system version

STM32

### Shell

ZSH

**Comment by mantriyogesh** [comment]
Can you please send the git commit you have used both sides and the logs both sides?

**Comment by lwj850533527** [comment]
Hi @mantriyogesh
git commit is:https://github.com/espressif/esp-hosted/commit/70de43ac9cc30ef55960d8025274df7a0fe1dfc8

the logs only 
`Failed to send control req`

I added printing and found that it return at hosted_get_semaphore(ctrl_req_sem)

**Comment by mantriyogesh** [comment]
Hello @lwj850533527 , Please give us time to reproduce and fix this.

**Comment by lwj850533527** [comment]
Hi @mantriyogesh
Has it been reproduced

**Comment by mantriyogesh** [comment]
Hello @lwj850533527 ,

I can check this issue earliest by Tuesday.

**Comment by mantriyogesh** [comment]
@lwj850533527 , Do you have esp side logs?

**Comment by mantriyogesh** [comment]
I would really appreciate it if you can provide full textual logs both sides..

**Comment by mantriyogesh** [comment]
I have not yet tested this, but I can confirm the race condition could be there, as you experienced in this code leg.

Can you please cross check if [ctrl_correct_sem.patch](https://github.com/user-attachments/files/17613565/ctrl_correct_sem.patch) solves your problems?

**Comment by lwj850533527** [comment]
> @lwj850533527 , Do you have esp side logs?

Esp side no command received, the log is empty
So I replied before,  the valid log is only `Failed to send control req`

**Comment by lwj850533527** [comment]
> I have not yet tested this, but I can confirm the race condition could be there, as you experienced in this code leg.
> 
> Can you please cross check if [ctrl_correct_sem.patch](https://github.com/user-attachments/files/17613565/ctrl_correct_sem.patch) solves your problems?

It can solve the issue
