### ISSUE TITLE
support for ESP32-C3?

### ISSUE THREAD

**Issue by gvdw** [espressif/esp-hosted#56]
Hi,  just wondering if/when BLE support for ESP32-C3 in hosted mode is planning to be implemented (looks like only WiFi at present)

Thanks

**Comment by mantriyogesh** [comment]
Hello @gvdw,

thanks for the query.
Yes Wi-Fi is implemented and BLE implementation is ongoing.
Most likely it will be in next commits.

**Comment by gvdw** [comment]
Awesome, thankyou @mantriyogesh !  I will close this for now and wait for the bleeding edge :)
