### ISSUE TITLE
Can the Smart Config app be used on this application?

### ISSUE THREAD

**Issue by mluisPlux** [espressif/esp-hosted#58]
Can the Smart Config app be used on this application?

**Comment by mantriyogesh** [comment]
Could you please let us know which type of configurations are you looking for?

**Comment by mluisPlux** [comment]
I need to provision the WIFI AP credentials using the smart config app. So i don't need to code them on the HOST MCU.

**Comment by mluisPlux** [comment]
I was thinking of using this https://github.com/espressif/esp-idf/tree/master/examples/provisioning/wifi_prov_mgr.
