### ISSUE TITLE
Where is the "pre-provided hosted mode firmware binary"?

### ISSUE THREAD

**Issue by ShonkyCH** [espressif/esp-hosted#6]
To try and avoid having to set up a build environment initially, where can I find the pre-compiled ESP32 binary mentioned in https://github.com/espressif/esp-hosted/blob/master/docs/Setup.md ?

Doesn't appear in the repo and I've not been able to find it. Where should I look please?

Thanks

**Comment by ShonkyCH** [comment]
Ok, well I seem to have built a working version that appears to run. I've not got it working yet but suspect some interface or config issues.

Either way I think it would be could to include a pre-built binary somewhere. The documentation is a bit light there and has a a couple of confusing mistakes. e.g. it refers to running "git mv" on an ESP32.

**Comment by MangeshMalusare** [comment]
Hi,
We will soon include pre-built binaries.

w.r.t kernel module compilation, we have provided a convenience script 'rpi_init.sh' which compiles and loads kernel module.
The script can be found in 'host/linux/host_control' directory.  Please refer 'Getting started' guide for more information.

Thanks,
Mangesh

**Comment by ShonkyCH** [comment]
Ah, right you are. Thanks. Not mentioned on the hardware setup page which I was reading first and it jumps straight into it working with the module loaded.

It's a bit disjointed. Hardware Setup & Compilation talks about cloning the repo and getting the kernel headers and last step is, 'here's it working'. So you need to jump across to the Getting Started page in the middle to do the kernel module compile.

**Comment by MangeshMalusare** [comment]
Thanks for your inputs! We will try to make it more organised and understandable in future versions.

**Comment by MangeshMalusare** [comment]
Prebuilt binaries are available now.
https://github.com/espressif/esp-hosted/releases

**Comment by MangeshMalusare** [comment]
Hi, can you please help close this issue?

**Comment by ameyinamdar** [comment]
Closing the issue as pre-built binaries are now available.
