### ISSUE TITLE
STM32 Host Blocking on assert(transaction_task_id);

### ISSUE THREAD

**Issue by mluisPlux** [espressif/esp-hosted#60]
My STM32 Host is Blocking on assert(transaction_task_id); on the spi_drv.c file. 
I'm using a STM32F7 board and a ESP32-C3.
![image](https://user-images.githubusercontent.com/90632159/133820628-58664885-4bdf-4aef-b03c-5558a06765b1.png)
Do you what might be the problem?

**Comment by mantriyogesh** [comment]
Could you please check if heap size could be increased?
It looks like memory not available.

**Comment by mluisPlux** [comment]
It worked.
