### ISSUE TITLE
mmc-bcm2835 3f300000.mmc: card claims to support voltages below defined range

### ISSUE THREAD

**Issue by nkhs** [espressif/esp-hosted#7]
![image](https://user-images.githubusercontent.com/29690436/92462010-809c4900-f1fc-11ea-82f9-7a834f29f069.png)

**Comment by nkhs** [comment]
I am using ESP32F-Kit, Raspberry Pi 3b

**Comment by ameyinamdar** [comment]
@nkhs I think ESP32F-kit may not have required pull-ups on SDIO pins. Can you please check the schematic of ESP32F-Kit?

**Comment by nkhs** [comment]
[ESP-32F开发板原理图.pdf](https://github.com/espressif/esp-hosted/files/5190376/ESP-32F.pdf)
This is my ESP32-F data sheet.

**Comment by ameyinamdar** [comment]
@nkhs There are no pull-ups on the SDIO pins (https://github.com/espressif/esp-hosted/blob/master/docs/Setup.md#hardware-setupconnections). Also, it looks like some of these pins are actually used to connect to some other peripherals on the board. Can you please use ESP32-WROVER-Kit instead as described in the link specified here?
