### ISSUE TITLE
what happens if i don't set bssid?

### ISSUE THREAD

**Issue by shchoi1** [espressif/esp-hosted#96]
in multiple ap with same ssid environment, if i don't set bssid, which ap to be connected?
does it connect to ap with strongest signal automatically?
or connect to anyone randomly?

**Comment by ajita02** [comment]
Hi @shchoi1,
Yes, It will connect to strongest signal AP.

Thanks,
Ajita

**Comment by shchoi1** [comment]
thank you ajita02
